{
  parserClass="com.bamuel.spllang.parser.SPLParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="SPL"
  psiImplClassSuffix="Impl"
  psiPackage="com.bamuel.spllang.psi"
  psiImplPackage="com.bamuel.spllang.psi.impl"

  elementTypeHolderClass="com.bamuel.spllang.psi.SPLTypes"
  elementTypeClass="com.bamuel.spllang.psi.SPLElementType"
  tokenTypeClass="com.bamuel.spllang.psi.SPLTokenType"
}

splFile ::= item_*

item_ ::=  declaration_ | statement_ | preprocessor_ | function_ | element_
    declaration_ ::= api_ | field_ | local_ | menu_ | mode_ | object_ | parameters_ | procedure_ | returning_ | screen_ | comments_

    statement_ ::= abort_ | accept_ | acknowledge_ | audit_ | back-to-detail_ | beginwork_ | box_ | break_ | call_ | callurl_ | checkbox_ | clear_ | close_ | command_ | commitwork_ | confirm_ | continue_
                 | continueentry_ | delete_ | disablealltriggers_ | display_ | do_ | do2_ | dropdown_ | exit_ | extract_ | field-group_ | for_ | get_ | if_ | initialise_ | insert_ | link_ | lock-method_ | message_ | messagebox_
                 | need_ | open_ | option_ | page_ | pause_ | pop_ | position_ | print_ | push_ | query_ | radio-button_ | re-enter_ | refresh_ | repeat_ | report_ | reportfinish_ | reportsection_ | reportsectionfinish_
                 | re-select_ | restore_ | rollbackwork_ | save_ | screengroup_ | screensection_ | select_ | serial_ | set_ | set2_ | set-date-validation_ | skip_ | sql-delete_ | sql-update_ | statement-group_ | stringstatement_ | switch_
                 | transaction_ | unlock_ | update_ | version-number_ | web-client-local-agent_ | while_ | comments_ | preprocessordefinedfunction_

    preprocessor_ ::= preprocessor_include_ | preprocessor_define_ | preprocessor_define2_ | preprocessor_undef_ | preprocessor_ifdef_ | preprocessor_ifndef_ | preprocessor_if_

    function_ ::= arithmeticfunction_  | datetimefunction_ | filehandlingfunction_ | environmentfunction_ | olefunction_ | stringfunction_ | securityfunction_ | xmlfunction_

        arithmeticfunction_ ::= aand_ | abs_ | anot_ | aor_ | cos_ | fraction_ | integer_ | lshift_ | max-value_ | max-presentation-value_
        | min-value_ | power-of_ | random_ | rshift_ | sign-of_ | sin_ | smallest-increment_ | square-root_ | sum_ | sum-array_ | tan_

        datetimefunction_ ::= add-month_ | client-date-time-string_ | date-from-date-time_ | date-time_ | date-to-julian_ | day_ | day-name_
        | days-in-month_ | dow_ | gmt_ | hour_ | julian_ | julian-to-date_ | leap-year_ | minute_ | month_ | month-name_ | second_
        | systime_ | time-from-date-time_ | time-zone_ | tod_ | today_ | year_

        filehandlingfunction_ ::= cd_ | cd-without-close-all_ | client-file-browse_ | dir_ | file-exists_ | file-name_ | file-owner_ | file-size_
        | file-status_ | file-version_ | finish-dir-search_ | is-a-dir_ | local-cd_ | local-cd-without-close-all_ | local-dir_ | mkdir_
        | modification-time_ | next-dir-entry_ | rmdir_ | start-dir-search_

        environmentfunction_ ::= activepid_ | apiapplication-name_ | batched_ | can-dee_ | check-auth_ | colour-picker_
        | create-db-schema_ | create-db-user_ | currency-sign_ | database-type_ | db-command_ | db-table-name_ | dde-error-status_
        | dde-execute_ | dde-initiate_ | dde-poke_ | dde-request_ | dde-terminate_ | delete-registry-value_ | enable-status-bar_
        | enable-system-menu_ | enable-tool-bar_ | error-description_ | escape_ | exit-status_ | find-parameter_ | getenv_ | get-field-value_
        | get-field-value-numeric_ | get-function-code_ | get-module-code_ | get-param_ | get-registry-enum-key_ | get-registry-enum-value_
        | get-registry-value_ | get-system-metrics_ | gid_ | grant-db-schema_ | hide-dockable-windows_ | idx_ | if-then-else_ | io-count_
        | line-no_ | local-no_ | login-id_ | mail-add-line_ | mail-attach_ | mail-cancel_ | mail-from-name_ | mail-reply-to_ | mail-send_
        | mail-start_ | max-screen-columns_ | max-screen-rows_ | message-status_ | mode-name_ | mouse-column_ | mouse-row_ | node-name_
        | occurrence_ | operating-system_ | page-no_ | param-cnt_ | pid_ | pronto-release_ | prouser-flags_ | refresh-quick-links_
        | report-is-xml_ | review-row_ | revoke-db-schema_ | rgb-to-colour_ | screen-mode_ | search_ | search-mode_ | set-app-user_
        | set-data-area-name_ | set-background-image_ | set-background-url_ | set-environment_ | set-function-code_ | set-help-context_
        | set-keyboard-focus_ | set-module-code_ | set-registry-value_ | set-web-window_ | sleep_ | spool-file-name_ | time-elapsed_
        | transaction-active_ | tty_ | uid_ | user-group_ | valid-activation-key_ | wait-for-input_

        olefunction_ ::= ole_addref_ | ole_advise_event_ | ole_bulk_put_ | ole_call_interactive_method_ | ole_call_method_ | ole_create_control_
                       | ole_create_instance_ | ole_enum_next_ | ole_enum_reset_ | ole_error_description_ | ole_get_active_object_ | ole_get_dispatch_id_
                       | ole_get_event_ | ole_get_property_ | ole_put_property_ | ole_put_property_byref_ | ole_query_interface_ | ole_release_
                       | ole_status_ | ole_unadvise_all_ | ole_unadvise_event_

        securityfunction_ ::= crc32_ | decrypt_ | encrypt_ | security_level_ | sign_data_ | verify_signed_data_

        stringfunction_ ::= ascii-char_ | ascii-num_ | base64toblob_| blobappend_ | blobappendbase64_ | blobsection_ | blobtobase64_
        | concat_ |  formatpicture_ | freeblob_ | fstr_ | leftjustify_ | lowercase_ | ltrim_ | maxalphavalue_ | num_ | paramtext_ | pattern_
        | readblobfromfile_ | reserved_ | rightjustify_ | rtrim_ | sizeof_ | sqlsubstring_ | strconcat_ | str_ | strlen_ | substring_
        | substringutf8_ | uppercase_ | validnumber_ | writeblobtofile_ | zstr_

        xmlfunction_ ::= xml_add_child_node_ | xml_add_child_node_blob_ | xml_add_child_node_clob_ | xml_add_child_node_no_quotes_ | xml_add_child_node_number_
                       | xml_add_child_node_text_ | xml_add_node_attribute_ | xml_add_ns_ | xml_child_node_blob_ | xml_child_node_clob_ | xml_child_node_text_
                       | xml_close_document_ | xml_copy_node_handle_ | xml_delete_node_ | xml_delete_node_attribute_ | xml_document_is_json_ | xml_free_node_handle_
                       | xml_get_child_by_name_ | xml_get_doc_encoding_ | xml_get_first_attribute_name_ | xml_get_first_child_node_ | xml_get_last_child_node_
                       | xml_get_next_attribute_name_ | xml_get_next_node_ | xml_get_node_attribute_ | xml_get_ns_prefix_url_ | xml_get_prev_node_ | xml_get_root_node_
                       | xml_modify_node_attribute_ | xml_modify_node_text_ | xml_new_document_ | xml_next_element_sibling_ | xml_node_blob_ | xml_node_clob_
                       | xml_node_name_ | xml_node_ns_prefix_ | xml_node_ns_url_ | xml_node_string_ | xml_node_text_ | xml_node_type_ | xml_parse_file_ | xml_parse_text_
                       | xml_prev_element_sibling_ | xml_save_as_file_ | xml_save_as_file_ex_ | xml_save_as_text_ | xml_save_as_text_ex_ | xml_set_json_array_
                       | xml_validate_doc_

//Statement rules
abort_ ::= ABORT string_ abortitems_
abortitems_ ::= ((PIC IS? picture_)| NOLOG)*
accept_ ::= ACCEPT identifier_ rowcol_ acceptitems_
acceptitems_ ::= (col_ | accepttitle_ | NOTITLE | MULTILINE | rows_ | columns_ | acceptpicture_ | BLANK_WHEN_ZERO | BLANK_DECIMALS_WHEN_ZERO | OPTIONAL | acceptdefault_ | acceptallow_ | acceptdisallow_ | JUSTIFY | AUTO_RETURN | timeout_ | acceptedits_ | acceptfill_ | acceptlookup_ | accpetcase_ | acceptjustify_ | accepthelp_ | BOLD | DIM | FLASHING | INVERSE | ITALIC | UNDERLINED | FOREGROUND | BACKGROUND | BLANK | acceptonerror_ | acceptfunctionkey_ | accepttag_ | accepthelpcontext_ | accepthelpscreen_ | when_ | SHOW_VALUE | NO_CLEAR | SUPPRESS | CONDITIONAL_SUPPRESS | READ_ONLY | FIXED_WIDTH_FONT | colour_ | beforeaccept_ | acceptvalidation_ | USE_VALIDATE_TRIGGER | acceptproceduralstatement_ scale_ | NO_WARNING | acceptonchange_)*
accepttitle_ ::= (TITLE|COLUMNTITLE) IS? string_ rowcol_?
rows_ ::= ROWS number_
columns_ ::= COLUMNS number_
acceptpicture_ ::= PIC IS? picture_
acceptdefault_ ::= DEFAULT IS? string_
acceptallow_ ::= ALLOW number_ (TO number_)*
acceptdisallow_ ::= DISALLOW number_ (TO number_)*
timeout_ ::= TIMEOUT IS? number_
acceptedits_ ::= EDIT (IS|ARE)? (string_)*
acceptfill_ ::= FILL WITH? (LEADING|TRAILING)? string_
acceptlookup_ ::= LOOKUP NOT? IN? string_ (ON INDEX (string_|number_)*)? (KEY IS? string_*)?
accpetcase_ ::= LOWERCASE | UPPERCASE
acceptjustify_ ::= LEFT | CENTRE | RIGHT | CENTRE_COORD | RIGHT_COORD
accepthelp_ ::= HELP IS? string_
acceptonerror_ ::= onerror_
acceptfunctionkey_ ::= ON FUNCTION_KEY statement_* END_ON
accepttag_ ::= TAG IS? NUMBER
accepthelpcontext_ ::= HELP_CONTEXT IS? string_ number_
accepthelpscreen_ ::= HELP_SCREEN SCREEN_PRIMARY identifier_ rowcol_ (OCCURS number_)? SHOWING identifier_ string_ (COMMA? identifier_ STRING)* (USING identifier_)
beforeaccept_ ::= BEFORE_ACCEPT statement_* END_BEFORE_ACCEPT
acceptvalidation_ ::= VALIDATIONS statement_* END_VALIDATIONS
acceptproceduralstatement_ ::= statement_*
scale_ ::= SCALE IS? number_
acceptonchange_ ::= ON CHANGE statement_* END_ON
acknowledge_ ::= ACKNOWLEDGE string_ (prompt_)?
audit_ ::= AUDIT (ON|OFF)? (identifier_)*
back-to-detail_ ::= BACK_TO_DETAIL
beginwork_ ::= BEGIN WORK beginworkitems_
beginworkitems_ ::= ((ON string_ (COMMA string_)*) | (LEAVING string_ (COMMA string_)*) | FREE_LOCKS | (onerror_))*
box_ ::= BOX boxitems_
boxitems_ ::= ((rowcol_ TO rowcol_) | DOUBLE | NO_CROSS | (TITLE IS? string_) | SUNKEN | colour_ | ABSOLUTE_COORDINATES)*
break_ ::= BREAK
call_ ::= CALL string_ callitems_
callitems_ ::= (parameters_ | max_parameters_ | returning_ | home_ | BATCH | LEAVE_FILES_OPEN | EXTERNAL | backgroundnowait | onerror_)*
max_parameters_ ::= MAX_PARAMETERS ARE? number_
home_ ::= HOME IS? string_
backgroundnowait_ ::= BACKGROUND | BACKGROUNDNOWAITWAIT
callurl_ ::= CALL_URL string_ callurlitems_
callurlitems_ ::= (httpheaders_ | httpbody_ | httpmethod_ | httpproxy_ | httpauthany_ | timeout_ | cacertificate_ | sslcertificate_ | sslkey_ | sslkeypassword_ | allowredirection_ | sftpcommand_ | sftppostcommand_ | sftpcreatedirs_ | urluser_ | urlloginoptions_ | callreturning_ | onerror_)*
httpheaders_ ::= HTTP_HEADERS ARE? (string_|FILE) IS? string_?
httpbody_ ::= HTTP_BODY (IS|IN)? (string_|FILE) IS? string_?
httpmethod_ ::= HTTP_METHOD IS? string_ //todo: http methods
httpproxy_ ::= HTTP_PROXY IS? string_
httpauthany_ ::= HTTP_AUTH_ANY
cacertificate_ ::= CA_CERTIFICATE IS? string_
sslcertificate_ ::= SSL_CERTIFICATE IS? string_
sslkey_ ::= SSL_KEY IS? string_ (SSL_KEY_PASSWORD IS? string_)?
allowredirection_ ::= ALLOW_REDIRECTION
sftpcommand_ ::= SFTP_COMMAND IS? string_
sftppostcommand_ ::= SFTP_POST_COMMAND IS? string_
sftpcreatedirs_ ::= SFTP_CREATE_DIRS
urluser_ ::= URL_USER IS? string_ (string_)?
urlloginoptions_ ::= URL_LOGIN_OPTIONS IS? string_
callreturning_ ::= RETURNING (HTTP_HEADERS IN? (string_|FILE) IS? string_?)? (HTTP_BODY IS (string_|FILE) IS? string_?)?
checkbox_ ::= CHECK_BOX string_ rowcol_ checkboxitems_
checkboxitems_ ::= ((VALUES string_ string_) | (TITLE string_) | colour_ | RIGHT_COORDINATE | (DEFAULT IS? (boolean_)) | READ_ONLY | (when_) | (BEFORE_CHECK_BOX statement_* END_BEFORE_CHECK_BOX) | (VALIDATIONS statement_* END_VALIDATIONS) | (ON CHANGE item_* END_ON) | CHECK_BOX_END)*
clear_ ::= CLEAR clearoptions_?
clearoptions_ ::= (ROWS number_ ((TO) number_)?) | (rowcol_ (TO) rowcol_) | (DATA) | (DATA|PROMPT rowcol_ TO rowcol_) | ABSOLUTE_COORDINATES
close_ ::= (CLOSE (string_ (("and remove") | (onerror_))*)) | (CLOSE ALL ("LOCAL"|"RECONNECT")?)
command_ ::= COMMAND string_ commanditems_
commanditems_ ::= (parameters_ | home_ | NO_MESSAGE | NO_REFRESH | NO_XTERM | max_parameters_ | BATCH | (BACKGROUND|BACKGROUNDNOWAITWAIT) | EXTERNAL | onerror_)*
commitwork_ ::= COMMIT WORK (onerror_)?
confirm_ ::= CONFIRM confirmitems_ CONFIRM_END
confirmitems_ ::= (rowcol_ | (AUTO (when_)?) | prompt_ | NO_PROMPT | (DEFAULT IS? boolean_) | (NO_WINDOW|WINDOW) | (BEFORE statement_*) | (CONFIRMED statement_*) | (NOT_CONFIRMED statement_*) | (AFTER statement_*))*
continue_ ::= CONTINUE
continueentry_ ::= CONTINUE_ENTRY
delete_ ::= DELETE string_ (NO_WARNING | onerror_)*
disablealltriggers_ ::= DISABLE_ALL_TRIGGERS
display_ ::= DISPLAY displayoptions_
displayoptions_ ::= displayoption1_ | displayoption2_
displayoption1_ ::= string_ rowcol_ displayoption1items_
displayoption1items_ ::= ((COL number_) | (PIC picture_) | (TITLE string_) | MULTILINE | (ROWS number_) | (COLUMNS number_) | BLANK_WHEN_ZERO | BLANK_DECIMALS_WHEN_ZERO | BOLD | DIM | FLASHING | INVERSE | ITALIC | UNDERLINED | BELL | FOREGROUND | BACKGROUND | DATA | PROMPT | colour_ | scale_ | FIXED_WIDTH_FONT | acceptjustify_ | (HELP_IS string_))*
displayoption2_ ::= BITMAP string_ rowcol_ (TO rowcol_)? BACKGROUNDNOWAITWAIT
do_ ::= DO string_ doitems_
doitems_ ::= ((SCREEN_MODE string_) | MODEENTRY | SEARCH | SAME | ONCE | SUB_SCREEN | (INITIAL_MODE IS | string_) | parameters_ | returning_ | (NEXT string_) | BACKGROUNDNOWAITWAIT | NO_SECTION)*
do2_ ::= DO NEXT string_
dropdown_ ::= DROP_DOWN dropdownitems_ DROP_DOWN_END
dropdownitems_ ::= (DYNAMIC | OPTIONAL | EDIT | (WIDTH IS? number_) | concat_title_)*
concat_title_ ::= CONCAT_TITLE (dropdownvalues_? | selectclauses_?)
dropdownvalues_ ::= (string_ TITLE string_)* | (ICON IS? string_)* | (when_ SHOW_VALUE?)
exit_ ::= EXIT number_? //todo: any number between -1 and 255
extract_ ::= EXTRACT identifier_ extractitems_ EXTRACT_END
extractitems_ ::= (ALL | ((NEXT|PREVIOUS) ((SAME|DIFFERENT) (identifier_ fieldclauses_)*)?) | LOCK | (ON INDEX (string_|number_)*) | (KEY IS? string_*) | (WHERE condition_) | (FINISH when_) | (onerror_) | (DETAIL statement_*) | (BEFORE (identifier_ fieldclauses_)* statement_*) | (AFTER (identifier_ fieldclauses_)* statement_*))*
field-group_ ::= FIELD_GROUP field-groupitems_ FIELD_GROUP_END
field-groupitems_ ::= ((when_) | (TITLE IS? string_) | VERTICAL | WRAP | (TAG IS? number_) | statement_*)*
for_ ::= FOR string_ EQUALTO condition_ DOWN? TO condition_ (STEP condition_)? DETAIL? statement_* FOR_END
get_ ::= GET ((identifier_ fieldclauses_)* FROM)? string_ getitems_
getitems_ ::= ((NEXT|PREVIOUS) | ((SAME|DIFFERENT) (identifier_ fieldclauses_)*) | (FROM | FIRST | LAST | CURRENT | LOOKUP) | (LOCK) | (ON INDEX (string_|number_)*) | (KEY IS? string_*) | onerror_)*
if_ ::= IF condition_ THEN? statement_* (ELSEIF condition_ THEN? statement_*)* (ELSE statement_*)? ENDIF
initialise_ ::= INITIALISE string_ (LEAVING string_ (COMMA string_)*)?
insert_ ::= INSERT string_ (LOCK | onerror_)*
link_ ::= LINK string_ NO_MAIN?
lock-method_ ::= LOCK_METHOD IS? (BACKGROUNDNOWAITWAIT|WAIT_WITH_TIMEOUT)?
message_ ::= MESSAGE (string_ | PIC IS? picture_)* (NOBELL)?
messagebox_ ::= MESSAGEBOX string_ messageboxitems_
messageboxitems_ ::= (messsageboxtitle_ | messageboxbuttons_ | messageboxdefault_ | messageboxicon_ | messageboxtag_ | messageboxhelpcontext_ | messageboxoptional_ | messageboxbell_)*
messsageboxtitle_ ::= TITLE IS? string_
messageboxbuttons_ ::= MESSAGEBOX_BUTTONS MESSAGEBOX_BUTTONS_VALUES
messageboxdefault_ ::= DEFAULT IS? MESSAGEBOX_BUTTONS_VALUES
messageboxicon_ ::= ICON IS? MESSAGEBOX_ICON_VALUES
messageboxtag_ ::= TAG IS? NUMBER
messageboxhelpcontext_ ::= HELP_CONTEXT string_ number_
messageboxoptional_ ::= OPTIONAL
messageboxbell_ ::= BELL
need_ ::= NEED string_ ("lines"|"LINES")? (ON string_)?
open_ ::= OPEN string_ openitems_
openitems_ ::= ((FILE IS? string_) | LOCK | CREATE | TRUNCATE | PERMANENTTEMPORARY | PRIVATE | NO_TRIGGERS | LOCAL | READ_ONLY | INDEX_ON_CLOSE | onerror_)*
option_ ::= OPTION string_ rowcol_ (TO rowcol_)? menuoption_ OPTION_END
//todo: buttonstyle values
menuoption_ ::= ((ROWS number_) | (COLUMNS number_) | (SECURITY string_? IS? number_) | (when_) | help_ | log_ | scale_ | colour_ | BOLD | ITALIC | UNDERLINED | (BITMAP IS? string_) | (BITMAP_PUSHED IS? string_) | (BITMAP_FOCUS IS? string_) | (BITMAP_HOVER IS? string_) | (BITMAP_GREYED IS? string_) | NO_ASPECT_RATIO | modeicon_ | (BUTTON_STYLE IS? string_) | (DEFAULT_BUTTON IS? string_) | (TEXT_POSITION IS? number_) | (HOTKEY IS? number_) | HIDDEN | ABSOLUTE_COORDINATES | NO_THEME | (DETAIL statement_*))*
log_ ::= LOG string_?
page_ ::= PAGE pageitems
pageitems ::= (NO_HEADER | NO_FOOTER | (ON string_))*
pause_ ::= PAUSE
pop_ ::= POP (string_ (LEAVING string_ (COMMA string_)*)? (LEAVING ALL)? )|((string_ (COMMA string_)*) FROM string_)
position_ ::= POSITION (BEFORE|AFTER)? string_ positionitems_
positionitems_ ::= ((ON INDEX (string_|number_)*) | (KEY IS? string_*) | (FIRST|LAST) | NO_WARNING)*
print_ ::= PRINT string_ printitems_ condition_* NO_NEWLINE? (ON string_)?
printitems_ ::= ((IN? COLUMN number_) | rowcol_ | (PIC IS? picture_) | BLANK_WHEN_ZERO | BLANK_DECIMALS_WHEN_ZERO | BOLD | UNDERLINED | ITALIC | (SUBSCRIPT|SUPERSCRIPT) | (FONT number_) | (STATIC) | colour_ | scale_ | (LEFT|RIGHT|CENTRE) | (SECTION IS? string_) | accepttag_)*
push_ ::= PUSH string_
query_ ::= QUERY string_ queryitems_
queryitems_ ::= (parameters_ | home_ | BATCH | NO_PAUSE | SPOOL | max_parameters_ | onerror_)*
radio-button_ ::= RADIO_BUTTON string_ (rowcol_ boolean_ TITLE string_ colour_?)* radio-buttonitems_ RADIO_BUTTON_END
radio-buttonitems_ ::= ((BUTTON_WHEN condition_) | (RIGHT_COORDINATE) | (DEFAULT IS? condition_) | (when_) | READ_ONLY | (BEFORE_RADIO_BUTTON statement_* END_BEFORE_RADIO_BUTTON) | (VALIDATIONS statement_* END_VALIDATIONS) | (ON CHANGE statement_* END_ON))*
re-enter_ ::= RE_ENTER (string_)? (OPTIONAL|AUTO)?
refresh_ ::= REFRESH (DATA|WHENS|PROMPTS|REVIEW|TITLE|string_)
repeat_ ::= REPEAT statement_* UNTIL condition_ statement_* REPEAT_END
report_ ::= REPORT string_ reportitems_
reportitems_ ::= ((FILE IS? string_) | (DIRECT (TO)? string_) | (NAME IS? string_) | (HEADER IS? string_) | (FOOTER IS? string_) | (WIDTH IS? condition_) | (DEPTH IS? condition_) | (LENGTH IS? condition_) | (MARGIN IS? condition_) | (DEFAULT FONT IS? condition_) | FULL_PAGE | (FORM TYPE IS? string_) NO_XML | SPOOL_ONLY | FULL_XML | NO_MESSAGE | onerror_)*
reportfinish_ ::= REPORT FINISHED (ON string_)?
reportsection_ ::= REPORT SECTION IS? string_? reportsectionitems_
reportsectionitems_ ::= ((HIDDEN|CAN_HIDE) | colour_ | (STYLE_CLASS IS? string_) | (ON string_))*
reportsectionfinish_ ::= REPORT SECTION FINISHED (ON string_)?
re-select_ ::= RE_SELECT
restore_ ::= RESTORE (string_ (LEAVING string_ (COMMA string_)*)? (LEAVING ALL)? )|((string_ (COMMA string_)*) FROM string_)
rollbackwork_ ::= ROLLBACK WORK (onerror_)?
save_ ::= SAVE string_
screengroup_ ::= SCREEN_GROUP screengroupitems_ statement_* SCREEN_GROUP_END
screengroupitems_ ::= ((when_) | (TITLE IS? string_) | (NEXT ROW) | HORIZONTAL | (WIDTH IS? number_) | (GROUP_STYLE IS? number_) | (TAG IS? number_))*
screensection_ ::= SCREEN_SECTION screensectionitems_  SCREEN_SECTION_END
screensectionitems_ ::= ((when_) | (TITLE IS? string_) | help_ | (SECTION_WHEN condition_) | ALWAYS_SHOW | (HIDDEN|HIDE)| do_)*
select_ ::= selectclauses_ selectitems_ SELECT_END
selectitems_ ::= ((onerror_)|(BEFORE statement_*)|(DETAIL statement_*)|(AFTER statement_*))*
selectclauses_ ::= SELECT DISTINCT? selectlist_* FROM (string_|COMMA)* (WHERE condition_)? (DATABASE_SQL|LOCAL_SQL)? (ORDER "by" (string_ DESC?)*)? (GROUP "by" string_*)? (HAVING condition_)? ((FOR UPDATE) | FOR_UPDATE)?
selectlist_ ::=  "*" | (identifier_ (COMMA identifier_)*)
serial_ ::= SERIAL string_ string_ serialitems_
serialitems_ ::= ((ON INDEX (string_|number_)*) | (KEY IS? string_*) |(onerror_)?)*
set_ ::= SET string_* assignmentoperator_ (condition_|string_*) (NO_WARNING)?
set2_ ::= SET (PAGE_NO|(DEFAULT FONT)) assignmentoperator_ condition_ (ON string_)?
assignmentoperator_ ::= "=" | "+=" | "-=" | "*=" | "/=" | "%="
set-date-validation_ ::= SET_DATE_VALIDATION accepthelpcontext_?
skip_ ::= SKIP ((condition_? ("lines")?)|(TO ("line")? condition_)) (ON string_)?
sql-delete_ ::= SQL_DELETE ALL? string_ (WHERE condition_)? (onerror_)?
sql-update_ ::= SQL_UPDATE ALL? string_ SET (identifier_ EQUALTO condition_)* (WHERE condition_)? (onerror_)? //todo: expression with subquery & procedural-statements
statement-group_ ::= STATEMENT_GROUP item_* STATEMENT_GROUP_END
stringstatement_ ::= stringstatement1_ | stringstatement2_ | stringstatement3_
stringstatement1_ ::= STRINGSTATMENT string_ (INSERTING|REPLACING) string_ "at" number_
stringstatement2_ ::= STRINGSTATMENT string_ DELETING "at"? arithmeticexpression_ (TO arithmeticexpression_)?
stringstatement3_ ::= STRINGSTATMENT string_ APPENDING string_
switch_ ::= SWITCH ON? string_ (CASE (string_|COMMA)* statement_*)* (ELSE statement_*)? SWITCH_END
transaction_ ::= TRANSACTION (transactionbegin_ | transactioncommit_ | transactionrollback_)
transactionbegin_ ::= BEGIN (ON string_ (COMMA STRING)*)? (LEAVING string_ (COMMA STRING)*)? FREE_LOCKS? (onerror_)?
transactioncommit_ ::= COMMIT (onerror_)?
transactionrollback_ ::= ROLLBACK (onerror_)?
unlock_ ::= UNLOCK (string_|ALL) LOCAL?
update_ ::= UPDATE (string_ IN)? string_ NO_WARNING? LOCK? (onerror_)?
version-number_ ::= VERSION_NUMBER IS? (number_|string_)
web-client-local-agent_ ::= WEB_CLIENT_LOCAL_AGENT (boolean_)
while_ ::= WHILE condition_ DETAIL? statement_* WHILE_END


//Arithmetic functions
aand_ ::= AAND LPAREN number_ COMMA number_ RPAREN
abs_ ::= ABS LPAREN number_ RPAREN
anot_ ::= ANOT LPAREN number_ RPAREN
aor_ ::= AOR LPAREN number_ COMMA number_ RPAREN
cos_ ::= COS LPAREN number_ RPAREN
fraction_ ::= FRACTION LPAREN number_ RPAREN
integer_ ::= INTEGER LPAREN number_ RPAREN
lshift_ ::= LSHIFT LPAREN number_ COMMA number_ RPAREN
max-value_ ::= MAX_VALUE LPAREN number_ RPAREN
max-presentation-value_ ::= MAX_PRESENTATION_VALUE LPAREN number_ RPAREN
min-value_ ::= MIN_VALUE LPAREN number_ RPAREN
power-of_ ::= POWER_OF LPAREN number_ COMMA number_ RPAREN
random_ ::= RANDOM LPAREN number_ RPAREN
rshift_ ::= RSHIFT LPAREN number_ COMMA number_ RPAREN
sign-of_ ::= SIGN_OF LPAREN number_ RPAREN
sin_ ::= SIN LPAREN number_ RPAREN
smallest-increment_ ::= SMALLEST_INCREMENT LPAREN number_ RPAREN
square-root_ ::= SQUARE_ROOT LPAREN number_ RPAREN
sum_ ::= SUM LPAREN number_ RPAREN
sum-array_ ::= SUM_ARRAY LPAREN number_ COMMA number_ COMMA number_ RPAREN
tan_ ::= TAN LPAREN number_ RPAREN

//Date and time functions
add-month_ ::= ADD_MONTH LPAREN datestring_ COMMA number_ COMMA number_ RPAREN
client-date-time-string_ ::= CLIENT_DATE_TIME_STRING LPAREN RPAREN
date-from-date-time_ ::= DATE_FROM_DATE_TIME LPAREN datestring_ COMMA boolean_ RPAREN
date-time_ ::= DATE_TIME LPAREN datestring_ COMMA datestring_ COMMA boolean_ RPAREN
date-to-julian_ ::= DATE_TO_JULIAN LPAREN string_ RPAREN
day_ ::= DAY LPAREN datestring_ RPAREN
day-name_ ::= DAY_NAME LPAREN datestring_ RPAREN
days-in-month_ ::= DAYS_IN_MONTH LPAREN number_ COMMA number_ RPAREN
dow_ ::= DOW LPAREN datestring_ RPAREN
gmt_ ::= GMT LPAREN RPAREN
hour_ ::= HOUR LPAREN datestring_ RPAREN //todo: stricter TIME
julian_ ::= JULIAN LPAREN number_ COMMA number_ COMMA number_ RPAREN
julian-to-date_ ::= JULIAN_TO_DATE LPAREN datestring_ RPAREN
leap-year_ ::= LEAP_YEAR LPAREN number_ RPAREN
minute_ ::= MINUTE LPAREN datestring_ RPAREN //todo: stricter TIME
month_ ::= MONTH LPAREN datestring_ RPAREN
month-name_ ::= MONTH_NAME LPAREN datestring_ RPAREN
second_ ::= SECOND LPAREN datestring_ RPAREN //todo: stricter TIME
systime_ ::= SYSTIME LPAREN RPAREN
time-from-date-time_ ::= TIME_FROM_DATE_TIME LPAREN datestring_ COMMA boolean_ RPAREN
time-zone_ ::= TIME_ZONE LPAREN RPAREN
tod_ ::= TOD LPAREN RPAREN
today_ ::= TODAY LPAREN RPAREN
year_ ::= YEAR LPAREN datestring_ RPAREN


// Environment function
activepid_ ::= ACTIVE_PID LPAREN number_ RPAREN
apiapplication-name_ ::= API_APPLICATION_NAME LPAREN RPAREN
batched_ ::= BATCHED LPAREN RPAREN
can-dee_ ::= CAN_DDE LPAREN RPAREN
check-auth_ ::= CHECK_AUTH LPAREN number_ RPAREN
colour-picker_ ::= COLOUR_PICKER LPAREN string_ RPAREN
create-db-schema_ ::= CREATE_DB_SCHEMA LPAREN string_ COMMA "SPACES" RPAREN
create-db-user_ ::= CREATE_DB_USER LPAREN string_ COMMA "SPACES" RPAREN
currency-sign_ ::= CURRENCY_SIGN LPAREN RPAREN
database-type_ ::= DATABASE_TYPE LPAREN RPAREN
db-command_ ::= DB_COMMAND LPAREN string_ RPAREN
db-table-name_ ::= DB_TABLE_NAME LPAREN string_ RPAREN
dde-error-status_ ::= DDE_ERROR_STATUS LPAREN RPAREN
dde-execute_ ::= DDE_EXECUTE LPAREN string_ COMMA string_ RPAREN
dde-initiate_ ::= DDE_INITIATE LPAREN string_ COMMA string_ RPAREN
dde-poke_ ::= DDE_POKE LPAREN string_ COMMA string_ COMMA string_ RPAREN
dde-request_ ::= DDE_REQUEST LPAREN string_ COMMA string_ RPAREN
dde-terminate_ ::= DDE_TERMINATE LPAREN string_ RPAREN
delete-registry-value_ ::= DELETE_REGISTRY_VALUE LPAREN string_ RPAREN
enable-status-bar_ ::= ENABLE_STATUS_BAR LPAREN boolean_ RPAREN
enable-system-menu_ ::= ENABLE_SYSTEM_MENU LPAREN boolean_ RPAREN
enable-tool-bar_ ::= ENABLE_TOOL_BAR LPAREN boolean_ RPAREN
error-description_ ::= ERROR_DESCRIPTION LPAREN number_ RPAREN
escape_ ::= ESCAPE LPAREN RPAREN
exit-status_ ::= EXIT_STATUS LPAREN RPAREN
find-parameter_ ::= FIND_PARAMETER LPAREN string_ RPAREN
getenv_ ::= GETENV LPAREN string_ RPAREN
get-field-value_ ::= GET_FIELD_VALUE LPAREN string_ RPAREN
get-field-value-numeric_ ::= GET_FIELD_VALUE_NUMERIC LPAREN string_ RPAREN
get-function-code_ ::= GET_FUNCTION_CODE LPAREN string_ RPAREN
get-module-code_ ::= GET_MODULE_CODE LPAREN string_ RPAREN
get-param_ ::= GET_PARAM LPAREN number_ RPAREN
get-registry-enum-key_ ::= GET_REGISTRY_ENUM_KEY LPAREN string_ COMMA number_ RPAREN
get-registry-enum-value_ ::= GET_REGISTRY_ENUM_VALUE LPAREN string_ COMMA number_ COMMA string_ RPAREN
get-registry-value_ ::= GET_REGISTRY_VALUE LPAREN string_ RPAREN
get-system-metrics_ ::= GET_SYSTEM_METRICS LPAREN number_ RPAREN
gid_ ::= GID LPAREN RPAREN
grant-db-schema_ ::= GRANT_DB_SCHEMA LPAREN string_ COMMA string_ RPAREN
hide-dockable-windows_ ::= HIDE_DOCKABLE_WINDOWS LPAREN (dockableflags_)? RPAREN
dockableflags_ ::= "0"| "non-zero"
idx_ ::= IDX LPAREN string_ (COMMA string_)* RPAREN
if-then-else_ ::= IF_THEN_ELSE LPAREN condition_ COMMA string_ COMMA string_ RPAREN //todo: condition
io-count_ ::= IO_COUNT LPAREN RPAREN
line-no_ ::= LINE_NO LPAREN RPAREN
local-no_ ::= LOCAL_NO_AND_LOCAL_YES LPAREN RPAREN
login-id_ ::= LOGIN_ID LPAREN RPAREN
mail-add-line_ ::= MAIL_ADD_LINE LPAREN string_ RPAREN
mail-attach_ ::= MAIL_ATTACH LPAREN string_ COMMA string_ COMMA number_ COMMA number_ COMMA number_ RPAREN
mail-cancel_ ::= MAIL_CANCEL LPAREN RPAREN
mail-from-name_ ::= MAIL_FROM_NAME LPAREN string_ RPAREN
mail-reply-to_ ::= MAIL_REPLY_TO LPAREN string_ COMMA string_ RPAREN
mail-send_ ::= MAIL_SEND LPAREN string_ COMMA boolean_ COMMA boolean_ RPAREN
mail-start_ ::= MAIL_START LPAREN string_ RPAREN
max-screen-columns_ ::= MAX_SCREEN_COLUMNS LPAREN RPAREN
max-screen-rows_ ::= MAX_SCREEN_ROWS LPAREN RPAREN
message-status_ ::= MESSAGE_STATUS LPAREN? RPAREN?
mode-name_ ::= MODE_NAME LPAREN RPAREN
mouse-column_ ::= MOUSE_COLUMN LPAREN RPAREN
mouse-row_ ::= MOUSE_ROW LPAREN RPAREN
node-name_ ::= NODE_NAME LPAREN RPAREN
occurrence_ ::= OCCURRENCE LPAREN string_ RPAREN
operating-system_ ::= OPERATING_SYSTEM LPAREN RPAREN
page-no_ ::= PAGE_NO LPAREN string_ RPAREN
param-cnt_ ::= PARAM_CNT LPAREN RPAREN
pid_ ::= PID LPAREN RPAREN
pronto-release_ ::= PRONTO_RELEASE LPAREN RPAREN
prouser-flags_ ::= PROUSER_FLAGS LPAREN RPAREN
refresh-quick-links_ ::= REFRESH_QUICK_LINKS LPAREN RPAREN
report-is-xml_ ::= REPORT_IS_XML LPAREN string_ RPAREN
review-row_ ::= REVIEW_ROW LPAREN RPAREN
revoke-db-schema_ ::= REVOKE_DB_SCHEMA LPAREN string_ COMMA string_ RPAREN
rgb-to-colour_ ::= RGB_TO_COLOUR LPAREN number_ RPAREN
screen-mode_ ::= SCREEN_MODE LPAREN RPAREN
search_ ::= SEARCH LPAREN RPAREN
search-mode_ ::= SEARCH_MODE LPAREN RPAREN
set-app-user_ ::= SET_APP_USER LPAREN string_ RPAREN
set-data-area-name_ ::= SET_DATA_AREA_NAME LPAREN string_ RPAREN
set-background-image_ ::= SET_BACKGROUND_IMAGE LPAREN string_ RPAREN
set-background-url_ ::= SET_BACKGROUND_URL LPAREN string_ COMMA background-urlflags_ RPAREN
background-urlflags_ ::= "1" | "2" | "4" | "8" //todo:  flag settings can be combined by adding the values together.
set-environment_ ::= SET_ENVIRONMENT LPAREN string_ COMMA string_ RPAREN
set-function-code_ ::= SET_FUNCTION_CODE LPAREN string_ RPAREN
set-help-context_ ::= SET_HELP_CONTEXT LPAREN string_ COMMA number_ RPAREN
set-keyboard-focus_ ::= SET_KEYBOARD_FOCUS LPAREN string_ COMMA string_ RPAREN //todo: 2nd string is flag not sure what the values are
set-module-code_ ::= SET_MODULE_CODE LPAREN string_ RPAREN
set-registry-value_ ::= SET_REGISTRY_VALUE LPAREN string_ COMMA string_ RPAREN
set-web-window_ ::= SET_WEB_WINDOW LPAREN string_ COMMA string_ COMMA string_ COMMA webwindowflag_ RPAREN
webwindowflag_ ::= "1" | "2" | "3" | "4" | "8" | "16" | "32" | "64" //todo:  flag settings can be combined by adding the values together.
sleep_ ::= SLEEP LPAREN number_ RPAREN
spool-file-name_ ::= SPOOL_FILE_NAME LPAREN (string_)? RPAREN
time-elapsed_ ::= TIME_ELAPSED LPAREN number_ COMMA number_ RPAREN
transaction-active_ ::= TRANSACTION_ACTIVE LPAREN RPAREN
tty_ ::= TTY LPAREN RPAREN
uid_ ::= UID LPAREN RPAREN
user-group_ ::= USER_GROUP LPAREN RPAREN
valid-activation-key_ ::= VALID_ACTIVATION_KEY LPAREN string_ COMMA string_ RPAREN
wait-for-input_ ::= WAIT_FOR_INPUT LPAREN RPAREN

//File handling functions
//FILEHANDLING_FUNCTIONS=(cd|cd-without-close-all|client-file-browse|dir|file-exists|file-name|file-owner|file-size|file-status|file-version|finish-dir-search|is-a-dir|local-cd|local-cd-without-close-all|local-dir|mkdir|modification-time|next-dir-entry|rmdir|start-dir-search)
cd_ ::= CD LPAREN string_ RPAREN
cd-without-close-all_ ::= CD_WITHOUT_CLOSE_ALL LPAREN string_ RPAREN
client-file-browse_ ::= CLIENT_FILE_BROWSE LPAREN string_ COMMA string_ COMMA browsefilters_* COMMA string_ COMMA browseflag_ RPAREN
browsefilters_ ::= "|" | "." | "*" | ";" | string_
browseflag_ ::= "1" | "2" | "4"
dir_ ::= DIR LPAREN RPAREN
file-exists_ ::= FILE_EXISTS LPAREN string_ COMMA number_ RPAREN
file-name_ ::= FILE_NAME LPAREN string_ RPAREN
file-owner_ ::= FILE_OWNER LPAREN string_ RPAREN
file-size_ ::= FILE_SIZE LPAREN string_ RPAREN
file-status_ ::= FILE_STATUS LPAREN RPAREN
file-version_ ::= FILE_VERSION LPAREN string_ RPAREN
finish-dir-search_ ::= FINISH_DIR_SEARCH LPAREN RPAREN
is-a-dir_ ::= IS_A_DIR LPAREN string_ RPAREN
local-cd_ ::= LOCAL_CD LPAREN RPAREN
local-cd-without-close-all_ ::= LOCAL_CD_WITHOUT_CLOSE_ALL LPAREN RPAREN
local-dir_ ::= LOCAL_DIR LPAREN RPAREN
mkdir_ ::= MKDIR LPAREN string_ RPAREN
modification-time_ ::= MODIFICATION_TIME LPAREN string_ RPAREN
next-dir-entry_ ::= NEXT_DIR_ENTRY LPAREN RPAREN
rmdir_ ::= RMDIR LPAREN string_ RPAREN
start-dir-search_ ::= START_DIR_SEARCH LPAREN (string_ COMMA string_)? RPAREN


//String functions
ascii-char_ ::= ASCII_CHAR LPAREN number_ RPAREN
ascii-num_ ::= ASCII_NUM LPAREN string_ RPAREN
base64toblob_ ::= BASE64TOBLOB LPAREN string_ COMMA string_ RPAREN
blobappend_ ::= BLOBAPPEND LPAREN string_ COMMA string_ RPAREN
blobappendbase64_ ::= BLOBAPPENDBASE64 LPAREN string_ COMMA string_ RPAREN
blobsection_ ::= BLOBSECTION LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
blobtobase64_ ::= BLOBTOBASE64 LPAREN string_ COMMA string_ COMMA string_ RPAREN
concat_ ::= CONCAT LPAREN string_ (COMMA? string_)* RPAREN
formatpicture_ ::= FORMATPICTURE LPAREN string_ COMMA picture_ RPAREN
freeblob_ ::= FREEBLOB LPAREN string_ RPAREN
fstr_ ::= FSTR LPAREN number_ COMMA number_ COMMA number_ RPAREN
leftjustify_ ::= LEFTJUSTIFY LPAREN string_ RPAREN
lowercase_ ::= LOWERCASE LPAREN string_ RPAREN
ltrim_ ::= LTRIM LPAREN string_ RPAREN
maxalphavalue_ ::= MAXALPHAVALUE LPAREN number_ RPAREN
num_ ::= NUM LPAREN string_ RPAREN
paramtext_ ::= PARAMTEXT LPAREN STRING (COMMA param_list_)? RPAREN
param_list_ ::= string_ (COMMA string_)*
pattern_ ::= PATTERN LPAREN string_ COMMA string_  RPAREN
readblobfromfile_ ::= READBLOBFROMFILE LPAREN string_ COMMA string_ RPAREN
reserved_ ::= RESERVED LPAREN string_ RPAREN
rightjustify_ ::= RIGHTJUSTIFY LPAREN string_ RPAREN
rtrim_ ::= RTRIM LPAREN string_ RPAREN
sizeof_ ::= SIZEOF LPAREN string_ RPAREN
sqlsubstring_ ::= SQLSUBSTRING LPAREN string_ COMMA number_ COMMA number_ RPAREN
strconcat_ ::= STRCONCAT LPAREN string_ (COMMA? string_)* RPAREN
str_ ::= STR_FUNC LPAREN number_ RPAREN
strlen_ ::= STRLEN LPAREN string_ RPAREN
substring_ ::= SUBSTRING LPAREN string_ COMMA number_ COMMA number_ RPAREN
substringutf8_ ::= SUBSTRINGUTF8 LPAREN string_ COMMA number_ COMMA number_ COMMA number_ RPAREN
uppercase_ ::= UPPERCASE LPAREN string_ RPAREN
validnumber_ ::= VALIDNUMBER LPAREN string_ RPAREN
writeblobtofile_ ::= WRITEBLOBTOFILE LPAREN string_ COMMA string_ RPAREN
zstr_ ::= ZSTR LPAREN number_ COMMA number_ COMMA number_ RPAREN

//Security functions
crc32_ ::= CRC32 LPAREN string_ COMMA string_ RPAREN
decrypt_ ::= DECRYPT LPAREN string_ COMMA string_ COMMA string_ RPAREN
encrypt_ ::= ENCRYPT LPAREN string_ COMMA string_ COMMA string_ RPAREN
security_level_ ::= SECURITY_LEVEL LPAREN RPAREN
sign_data_ ::= SIGN_DATA LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
verify_signed_data_ ::= VERIFY_SIGNED_DATA LPAREN string_ COMMA string_ COMMA string_ COMMA string_ COMMA string_ RPAREN

//OLE functions
ole_addref_ ::= OLE_ADDREF LPAREN string_ RPAREN
ole_advise_event_ ::= OLE_ADVISE_EVENT LPAREN string_ COMMA string_ COMMA string_ RPAREN
ole_bulk_put_ ::= OLE_BULK_PUT LPAREN boolean_ RPAREN
ole_call_interactive_method_ ::= OLE_CALL_INTERACTIVE_METHOD LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
ole_call_method_ ::= OLE_CALL_METHOD LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
ole_create_control_ ::= OLE_CREATE_CONTROL LPAREN string_ COMMA number_ COMMA number_ COMMA number_ COMMA number_ RPAREN
ole_create_instance_ ::= OLE_CREATE_INSTANCE LPAREN string_ COMMA string_ RPAREN
ole_enum_next_ ::= OLE_ENUM_NEXT LPAREN string_ COMMA string_ RPAREN
ole_enum_reset_ ::= OLE_ENUM_RESET LPAREN string_ RPAREN
ole_error_description_ ::= OLE_ERROR_DESCRIPTION LPAREN number_ RPAREN
ole_get_active_object_ ::= OLE_GET_ACTIVE_OBJECT LPAREN string_ RPAREN
ole_get_dispatch_id_ ::= OLE_GET_DISPATCH_ID LPAREN string_ COMMA string_ RPAREN
ole_get_event_ ::= OLE_GET_EVENT LPAREN string_ COMMA string_ RPAREN
ole_get_property_ ::= OLE_GET_PROPERTY LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
ole_put_property_ ::= OLE_PUT_PROPERTY LPAREN string_ COMMA string_ COMMA string_ RPAREN
ole_put_property_byref_ ::= OLE_PUT_PROPERTY_BYREF LPAREN string_ COMMA string_ COMMA string_ RPAREN
ole_query_interface_ ::= OLE_QUERY_INTERFACE LPAREN string_ COMMA string_ RPAREN
ole_release_ ::= OLE_RELEASE LPAREN number_ RPAREN
ole_status_ ::= OLE_STATUS LPAREN RPAREN
ole_unadvise_all_ ::= OLE_UNADVISE_ALL LPAREN string_ RPAREN
ole_unadvise_event_ ::= OLE_UNADVISE_EVENT LPAREN string_ COMMA string_ RPAREN

//XML functions
xml_add_child_node_ ::= XML_ADD_CHILD_NODE LPAREN string_ COMMA string_ COMMA string_ RPAREN
xml_add_child_node_blob_ ::= XML_ADD_CHILD_NODE_BLOB LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_add_child_node_clob_ ::= XML_ADD_CHILD_NODE_CLOB LPAREN string_ COMMA string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_add_child_node_no_quotes_ ::= XML_ADD_CHILD_NODE_NO_QUOTES LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_add_child_node_number_ ::= XML_ADD_CHILD_NODE_NUMBER LPAREN string_ COMMA string_ COMMA string_ COMMA number_ COMMA number_ RPAREN
xml_add_child_node_text_ ::= XML_ADD_CHILD_NODE_TEXT LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_add_node_attribute_ ::= XML_ADD_NODE_ATTRIBUTE LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_add_ns_ ::= XML_ADD_NS LPAREN string_ COMMA string_ COMMA string_ RPAREN
xml_child_node_blob_ ::= XML_CHILD_NODE_BLOB LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_child_node_clob_ ::= XML_CHILD_NODE_CLOB LPAREN string_ COMMA string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_child_node_text_ ::= XML_CHILD_NODE_TEXT LPAREN string_ COMMA string_ COMMA string_ RPAREN
xml_close_document_ ::= XML_CLOSE_DOCUMENT LPAREN string_ RPAREN
xml_copy_node_handle_ ::= XML_COPY_NODE_HANDLE LPAREN string_ RPAREN
xml_delete_node_ ::= XML_DELETE_NODE LPAREN string_ RPAREN
xml_delete_node_attribute_ ::= XML_DELETE_NODE_ATTRIBUTE LPAREN string_ COMMA string_ COMMA string_ RPAREN
xml_document_is_json_ ::= XML_DOCUMENT_IS_JSON LPAREN string_ RPAREN
xml_free_node_handle_ ::= XML_FREE_NODE_HANDLE LPAREN string_ RPAREN
xml_get_child_by_name_ ::= XML_GET_CHILD_BY_NAME LPAREN string_ COMMA string_ COMMA string_ RPAREN
xml_get_doc_encoding_ ::= XML_GET_DOC_ENCODING LPAREN string_ RPAREN
xml_get_first_attribute_name_ ::= XML_GET_FIRST_ATTRIBUTE_NAME LPAREN string_ COMMA ("0"|"Non zero") RPAREN
xml_get_first_child_node_ ::= XML_GET_FIRST_CHILD_NODE LPAREN string_ RPAREN
xml_get_last_child_node_ ::= XML_GET_LAST_CHILD_NODE LPAREN string_ RPAREN
xml_get_next_attribute_name_ ::= XML_GET_NEXT_ATTRIBUTE_NAME LPAREN string_ COMMA ("0"|"Non zero") RPAREN
xml_get_next_node_ ::= XML_GET_NEXT_NODE LPAREN string_ RPAREN
xml_get_node_attribute_ ::= XML_GET_NODE_ATTRIBUTE LPAREN string_ COMMA string_ RPAREN
xml_get_ns_prefix_url_ ::= XML_GET_NS_PREFIX_URL LPAREN string_ COMMA string_ RPAREN
xml_get_prev_node_ ::= XML_GET_PREV_NODE LPAREN string_ RPAREN
xml_get_root_node_ ::= XML_GET_ROOT_NODE LPAREN string_ RPAREN
xml_modify_node_attribute_ ::= XML_MODIFY_NODE_ATTRIBUTE LPAREN string_ COMMA string_ COMMA string_ RPAREN
xml_modify_node_text_ ::= XML_MODIFY_NODE_TEXT LPAREN string_ COMMA string_ RPAREN
xml_new_document_ ::= XML_NEW_DOCUMENT LPAREN string_ COMMA string_ RPAREN
xml_next_element_sibling_ ::= XML_NEXT_ELEMENT_SIBLING LPAREN string_ RPAREN
xml_node_blob_ ::= XML_NODE_BLOB LPAREN string_ COMMA string_ RPAREN
xml_node_clob_ ::= XML_NODE_CLOB LPAREN string_ COMMA string_ COMMA string_ RPAREN
xml_node_name_ ::= XML_NODE_NAME LPAREN string_ RPAREN
xml_node_ns_prefix_ ::= XML_NODE_NS_PREFIX LPAREN string_ RPAREN
xml_node_ns_url_ ::= XML_NODE_NS_URL LPAREN string_ RPAREN
xml_node_string_ ::= XML_NODE_STRING LPAREN string_ RPAREN
xml_node_text_ ::= XML_NODE_TEXT LPAREN string_ RPAREN
xml_node_type_ ::= XML_NODE_TYPE LPAREN string_ RPAREN
xml_parse_file_ ::= XML_PARSE_FILE LPAREN string_ RPAREN
xml_parse_text_ ::= XML_PARSE_TEXT LPAREN string_ RPAREN
xml_prev_element_sibling_ ::= XML_PREV_ELEMENT_SIBLING LPAREN string_ RPAREN
xml_save_as_file_ ::= XML_SAVE_AS_FILE LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_save_as_file_ex_ ::= XML_SAVE_AS_FILE_EX LPAREN string_ COMMA string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_save_as_text_ ::= XML_SAVE_AS_TEXT LPAREN string_ COMMA string_ COMMA string_ RPAREN
xml_save_as_text_ex_ ::= XML_SAVE_AS_TEXT_EX LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
xml_set_json_array_ ::= XML_SET_JSON_ARRAY LPAREN string_ RPAREN
xml_validate_doc_ ::= XML_VALIDATE_DOC LPAREN string_ COMMA string_ RPAREN

// Preprocessor rule
preprocessor_include_ ::= PREPROCESSOR_INCLUDE STRING
preprocessor_define_ ::= PREPROCESSOR_DEFINE identifier_ LPAREN? (identifier_|COMMA)* RPAREN? (statement_)*
preprocessor_define2_ ::= PREPROCESSOR_DEFINE identifier_ (STRING|NUMBER|identifier_|picture_)
preprocessor_undef_ ::= PREPROCESSOR_UNDEF string_
preprocessor_ifdef_ ::= PREPROCESSOR_IFDEF string_ item_* (PREPROCESSOR_ELSE item_*)? PREPROCESSOR_ENDIF?
preprocessor_ifndef_ ::= PREPROCESSOR_IFNDEF string_ item_* (PREPROCESSOR_ELSE item_*)? PREPROCESSOR_ENDIF?
preprocessor_if_ ::= PREPROCESSOR_IF condition_ item_* (PREPROCESSOR_ELSE item_*)? PREPROCESSOR_ENDIF?


// Screen rule
screen_ ::= SCREEN identifier_ screenitems_ SCREEN_END
screenitems_ ::= (SCREEN_RESPONSIVE | window_ | windowpositision_ | screentitle_ | screenprimary_ | screenselect_ | screenquicklink_ | colour_ | screenreview_ | screenallowed_ | SCREEN_PROMPT_FOR_SEARCH | SCREEN_FIND_FOR_CURRENCY | screenprompt_ | screendatagrid_ | screenreviewoccurs | SCREEN_REVIEW_FROM_START | SCREEN_NO_REVIEW_ROW_SEPARATORS | SCREEN_NO_REVIEW_COLUMN_SEPARATORS | SCREEN_NO_REVIEW_SEPARATORS | SCREEN_START_ON_CURRENT_RECORD | SCREEN_LEAVE_PARENT_SCREEN | when_ | local_ | parameters_ | returning_ | STOP_EXIT_ALL_KEY | SCREEN_POSITION_ON_OK | SCREEN_STAY_IN_CORRECT | SCREEN_FORM_ENTRY | screenhelpcontext_ | before_ | detail_ | after_ | comments_)*

screentitle_ ::= TITLE IS? string_
screenprimary_ ::= SCREEN_PRIMARY identifier_ (ON INDEX (string_|number_)*)? ((SAME|DIFFERENT) (identifier_ fieldclauses_)*)?
screenselect_ ::= selectclauses_
screenquicklink_ ::= SCREEN_QUICK_LINK (ON)? identifier_
screenreview_ ::= REVIEW colour_
screenallowed_ ::= SCREEN_ALLOWED (IS|ARE)? (MODEENTRY|"FIND"|"NEXT"|"PREV"|"NEXT-SCR"|"PREV-SCR"|"SEARCH"|"ENTRY"|"CORRECT"|"REMOVE"|"find"|"next"|"prev"|"next-scr"|"prev-scr"|"search"|"entry"|"correct"|"remove")* identifier_* //todo: [mode-name ...]]
screenprompt_ ::= PROMPT rowcol_
screendatagrid_ ::= SCREEN_DATA_GRID
screenreviewoccurs ::= REVIEW OCCURS number_ ("by" number_)?
when_ ::= WHEN condition_

// API rule
api_ ::= API identifier_ procedureclauses_ API_END

// Field rule
field_ ::= FIELD (identifier_ fieldclauses_)*
fieldclauses_ ::= (fieldtype_ | fieldpic_ | fieldoccurs_ | fieldlike_ | fieldcase_ | JUSTIFY | USE_NAME_IN_DB | fielddbcolumnname_ | fielddrillback_ | comments_)*
fieldtype_ ::= TYPE IS? datatypes_
datatypes_ ::= ("NUMERIC"|"DECIMAL"|"MONEY"|"FLOATING"|"ALPHA"|"STRING"|"VARCHAR"|"BLOB"|"XML-HANDLE"|"DATE"|"TIME"|"DATE-TIME"|"DATETIME"|"DATE_TIME"|"LOCAL-DATE-TIME"|"BOOLEAN"|"COLOUR"|"COLOR"|"OLE-INTERFACE"|"numeric"|"decimal"|"money"|"floating"|"alpha"|"string"|"varchar"|"blob"|"xml-handle"|"date"|"time"|"date-time"|"datetime"|"date_time"|"local-date-time"|"boolean"|"colour"|"color"|"ole-interface")
fieldpic_ ::= PIC IS? picture_
fieldoccurs_ ::= OCCURS NUMBER ("times")?
fieldlike_ ::= LIKE identifier_
fieldcase_ ::= ("UPPERCASE" | "LOWERCASE" | "uppercase" | "lowercase")
fielddbcolumnname_ ::= DB_COLUMN_NAME IS? string_
fielddrillback_ ::= DRILL_BACK IS? string_

// Local field rule
local_ ::= LOCAL (FIELD)? (identifier_ fieldclauses_)*

// Menu rule
menu_ ::= MENU identifier_ menucaluses_ MENU_END
menucaluses_ ::= (window_ | windowpositision_ | local_ | parameters_ | returning_ | menubuttonwidth_ | STOP_EXIT_ALL_KEY | TITLE IS? string_ | TREEMENU | NOHIDE | colour_ | export_ | helpcontext_ | before_ | detail_ | after_ | comments_)*
menubuttonwidth_ ::= MENU_BUTTON_WIDTH IS? number_

// Mode rule
mode_ ::= MODE (identifier_|MODEENTRY) modeclauses_
modeclauses_ ::= (prompt_ | help_ | security_ | modeentry_ | process_ | modecurrency_ | LOCK | modeperform_ | when_ | colour_ | modeicon_ | alwaysshowaddnohide_ | comments_)*
prompt_ ::= PROMPT IS? string_
help_ ::= HELP IS? string_
security_ ::= SECURITY IS? number_
modeentry_ ::= MODEENTRY
process_ ::= PROCESS
modecurrency_ ::= MODECURRENCY
modeperform_ ::= PERFORM identifier_
modeicon_ ::= ICON IS? modeiconlist_
modeiconlist_ ::= "FOLDER-ICON"
                | "ADMIN-FOLDER-ICON"
                | "REPORT-FOLDER-ICON"
                | "ADMIN-ICON"
                | "REPORT-ICON"
                | "SCREEN-ICON"
                | "TRANSACTION-ICON"
                | "PERIOD-END-ICON"
                | "QUESTION-ICON"
                | "BLANK-ICON"
                | "FAVOURITES-FOLDER-ICON"
                | "LOCKED-FOLDER-ICON"
                | "BLUE-FOLDER-ICON"
                | "RED-FOLDER-ICON"
                | "GREEN-FOLDER-ICON"
                | "ENQUIRY-FOLDER-ICON"
alwaysshowaddnohide_ ::= (ALWAYS_SHOW|ALWAYS_ADD|NOHIDE)


// Object rule
object_ ::= OBJECT (identifier_ objectclauses_)*
objectclauses_ ::= (objectlike_ | objecttype_ | objectseparator_ | objectfile_ | objectrecord_ | objectkey_ | NOJOINS | NOROWID | comments_)*
objectlike_ ::= LIKE identifier_
objecttype_ ::= TYPE IS? filetypes_
filetypes_ ::= ("EXTERNAL"|"TEXT"|"SEQUENTIAL"|"FIXED-LENGTH-TEXT"|"INDEXED"|"ISAM"|"PRN"|"CSV"|"DB-SEQUENTIAL"|"MEMORY"|"external"|"text"|"sequential"|"fixed-length-text"|"indexed"|"isam"|"prn"|"csv"|"db-sequential"|"memory")
objectseparator_ ::= SEPARATOR IS? string_
objectfile_ ::= FILE IS? string_
objectrecord_ ::= RECORD IS? (identifier_ fieldclauses_)* RECORD_END
objectkey_ ::= KEY IS? (identifier_ (DESC)? (UNIQUE)? (DB_INDEX_ONLY)? (COMPRESS)?)*

// Parameters rule
parameters_ ::= PARAMETERS (ARE|IS)? ((identifier_ fieldclauses_)|string_)*

// Returning rule
returning_ ::= RETURNING (identifier_ fieldclauses_)*

// Procedure rule
procedure_ ::= PROCEDURE identifier_ procedureclauses_ PROCEDURE_END
procedureclauses_ ::= (window_ | relative_ | NOHIDE | windowpositision_ | colour_ | local_ | parameters_ | returning_ | STOP_EXIT_ALL_KEY | TITLE string_ | export_ | AUTO_TRANSACTION | helpcontext_ | comments_)* statement_*

// Other rules
export_ ::= EXPORT (CAN_OVERRIDE)?
colour_ ::= COLOUR IS? (colournames_) (ON colournames_)?
colournames_ ::= COLOUR_NAME|NUMBER|number_
helpcontext_ ::= HELP_CONTEXT IS? string_ number_
window_ ::= WINDOW (rowcol_ TO rowcol_)? (relative_)?
relative_ ::= RELATIVE TO rowcol_
windowpositision_ ::= WINDOW_POSITION IS? number_
before_ ::= BEFORE statement_*
detail_ ::= DETAIL statement_*
after_ ::= AFTER statement_*
onerror_ ::= ON ERROR (number_)? statement_* (ELSE statement_*)? END_ON

//row and col
//Syntax @row,col
rowcol_ ::= AT NUMBER COMMA NUMBER

condition_ ::= LPAREN* NOT? relationalexpression_ (LPAREN|RPAREN)* (logicaloperator_ condition_)? RPAREN*
logicaloperator_ ::= AND | OR | NOT | BETWEEN

relationalexpression_ ::= (arithmeticexpression_|string_) (relationaloperator_ (inlist_|arithmeticexpression_|string_|calusesValues_))? | NOT? relationalexpression_
relationaloperator_ ::= (ASCII_NUM | COLLATE)? (GREATERTHAN | LESSTHAN | EQUALTO | NOTEQUALTO | GREATERTHANOREQUALTO | LESSTHANOREQUALTO | (NOT? LIKE) | (NOT? IN))

arithmeticexpression_ ::= (LPAREN|RPAREN)* number_ (LPAREN|RPAREN)* (arithmeticoperator_ arithmeticexpression_)? (LPAREN|RPAREN)*
arithmeticoperator_ ::= ADD | SUBTRACT | MULTIPLY | DIVIDE | MODULUS
inlist_ ::= (LBRACE|LPAREN) ((function_|string_|number_) COMMA?)* (RBRACE|RPAREN)

calusesValues_ ::= MESSAGEBOX_BUTTONS_VALUES | MESSAGEBOX_ICON_VALUES | MODEENTRY | COLOUR_NAME

identifier_ ::= ":"? IDENTIFIER ((LBRACE (number_|MULTIPLY) RBRACE)|DOT (number_|MULTIPLY))*
string_ ::= STRING | identifier_ | PREDEFINED | COLOUR_NAME | function_ | arithmeticexpression_
number_ ::= NUMBER | identifier_ | PREDEFINED | function_ | arithmeticexpression_
boolean_ ::= PREDEFINED | "1" | "0" | function_
datestring_ ::= DATE | TIME | identifier_ | PREDEFINED | datetimefunction_ | modification-time_
preprocessordefinedfunction_ ::= IDENTIFIER LPAREN (string_|NUMBER|COMMA)* RPAREN
//The following picture string characters are used to specify the format of a field being defined.
// They indicate the size of the field, number of integer/decimal places and whether the field allows negative amounts.
// todo: add more picture string characters, this covers the basics.
picture_ ::= pic_group_ | pic_words
pic_words ::= "ddmmmyybhh:mm"| "HH:MM:SS" | STRING  // Date and time format
pic_group_ ::= ("$")* (NUMBER | identifier_) (LPAREN number_ RPAREN)? ((NUMBER | identifier_) LPAREN number_ RPAREN)? ("DR"|"CR")?
comments_ ::= COMMENT | BLOCK_COMMENT

element_ ::= FUNCTION_DECLARATION
           | PREDEFINED
           | STRING
           | NUMBER
           | IDENTIFIER
           | comments_
           | TITLE
           | DEFAULT
           | WINDOW
           | PROMPT
           | DETAIL
           | ICON
           | TAG
           | HELP_CONTEXT
           | OPTIONAL
           | BELL
           | NOBELL
           | COLOUR
           | TYPE
           | PIC
           | OCCURS
           | LIKE
           | JUSTIFY
           | USE_NAME_IN_DB
           | DB_COLUMN_NAME
           | DRILL_BACK
           | RELATIVE
           | WINDOW_POSITION
           | PARAMETERS
           | RETURNING
           | STOP_EXIT_ALL_KEY
           | EXPORT
           | CAN_OVERRIDE
           | BEFORE
           | AFTER
           | SEPARATOR
           | FILE
           | RECORD
           | RECORD_END
           | KEY
           | DESC
           | UNIQUE
           | DB_INDEX_ONLY
           | COMPRESS
           | NOJOINS
           | NOROWID
           | COLUMNTITLE
           | NOLOG
           | NOTITLE
           | MULTILINE
           | ROWS
           | COLUMNS
           | BLANK_WHEN_ZERO
           | BLANK_DECIMALS_WHEN_ZERO
           | ALLOW
           | DISALLOW
           | AUTO_RETURN
           | TIMEOUT
           | EDIT
           | FILL
           | LOOKUP
           | LEFT
           | CENTRE
           | RIGHT
           | CENTRE_COORD
           | RIGHT_COORD
           | BOLD
           | DIM
           | FLASHING
           | INVERSE
           | ITALIC
           | UNDERLINED
           | FOREGROUND
           | BACKGROUND
           | BLANK
           | ERROR
           | END_ON
           | FUNCTION_KEY
           | HELP_SCREEN
           | SHOWING
           | USING
           | SHOW_VALUE
           | NO_CLEAR
           | SUPPRESS
           | CONDITIONAL_SUPPRESS
           | READ_ONLY
           | FIXED_WIDTH_FONT
           | BEFORE_ACCEPT
           | END_BEFORE_ACCEPT
           | VALIDATIONS
           | END_VALIDATIONS
           | USE_VALIDATE_TRIGGER
           | SCALE
           | NO_WARNING
           | CHANGE
           | LEAVING
           | FREE_LOCKS
           | DOUBLE
           | NO_CROSS
           | SUNKEN
           | ABSOLUTE_COORDINATES
           | MAX_PARAMETERS
           | HOME
           | BATCH
           | LEAVE_FILES_OPEN
           | EXTERNAL
           | BACKGROUNDNOWAITWAIT
           | HTTP_HEADERS
           | HTTP_BODY
           | HTTP_METHOD
           | HTTP_PROXY
           | HTTP_AUTH_ANY
           | CA_CERTIFICATE
           | SSL_CERTIFICATE
           | SSL_KEY
           | SSL_KEY_PASSWORD
           | ALLOW_REDIRECTION
           | SFTP_COMMAND
           | SFTP_POST_COMMAND
           | SFTP_CREATE_DIRS
           | URL_USER
           | URL_LOGIN_OPTIONS
           | VALUES
           | RIGHT_COORDINATE
           | BEFORE_CHECK_BOX
           | END_BEFORE_CHECK_BOX
           | MESSAGEBOX_BUTTONS
           | DATA
           | NO_MESSAGE
           | NO_REFRESH
           | NO_XTERM
           | AUTO
           | NO_PROMPT
           | NO_WINDOW
           | CONFIRMED
           | NOT_CONFIRMED
           | COL
           | BITMAP
           | HELP_IS
           | SAME
           | ONCE
           | SUB_SCREEN
           | INITIAL_MODE
           | NEXT
           | NO_SECTION
           | DYNAMIC
           | CONCAT_TITLE
           | WIDTH
           | PREVIOUS
           | FINISH
           | ALL
           | WHERE
           | WRAP
           | VERTICAL
           | DOWN
           | STEP
           | SCREEN_RESPONSIVE
           | SCREEN_PRIMARY
           | INDEX
           | DIFFERENT
           | SCREEN_QUICK_LINK
           | SCREEN_ALLOWED
           | SCREEN_PROMPT_FOR_SEARCH
           | SCREEN_FIND_FOR_CURRENCY
           | SCREEN_DATA_GRID
           | SCREEN_REVIEW_FROM_START
           | SCREEN_NO_REVIEW_ROW_SEPARATORS
           | SCREEN_NO_REVIEW_COLUMN_SEPARATORS
           | SCREEN_NO_REVIEW_SEPARATORS
           | SCREEN_START_ON_CURRENT_RECORD
           | SCREEN_LEAVE_PARENT_SCREEN
           | WHEN
           | SCREEN_POSITION_ON_OK
           | SCREEN_STAY_IN_CORRECT
           | SCREEN_FORM_ENTRY
           | AUTO_TRANSACTION
           | TREEMENU
           | NOHIDE
           | MENU_BUTTON_WIDTH
           | HELP
           | SECURITY
           | PROCESS
           | MODECURRENCY
           | LOCK
           | PERFORM
           | ALWAYS_SHOW
           | ALWAYS_ADD
           | FROM
           | FIRST
           | LAST
           | CURRENT
           | THEN
           | ELSE
           | ELSEIF
           | NO_MAIN
           | WAIT_WITH_TIMEOUT
           | CREATE
           | TRUNCATE
           | PERMANENTTEMPORARY
           | PRIVATE
           | NO_TRIGGERS
           | INDEX_ON_CLOSE
           | LOG
           | BITMAP_PUSHED
           | BITMAP_FOCUS
           | BITMAP_HOVER
           | BITMAP_GREYED
           | NO_ASPECT_RATIO
           | BUTTON_STYLE
           | DEFAULT_BUTTON
           | TEXT_POSITION
           | HOTKEY
           | HIDDEN
           | NO_THEME
           | NO_HEADER
           | NO_FOOTER
           | ON
           | COLUMN
           | SUBSCRIPT
           | SUPERSCRIPT
           | FONT
           | SECTION
           | NO_NEWLINE
           | NO_PAUSE
           | SPOOL
           | BUTTON_WHEN
           | BEFORE_RADIO_BUTTON
           | END_BEFORE_RADIO_BUTTON
           | WHENS
           | PROMPTS
           | REVIEW
           | UNTIL
           | DIRECT
           | NAME
           | HEADER
           | FOOTER
           | DEPTH
           | LENGTH
           | MARGIN
           | FULL_PAGE
           | FORM
           | NO_XML
           | SPOOL_ONLY
           | FULL_XML
           | CAN_HIDE
           | STYLE_CLASS
           | ROW
           | GROUP_STYLE
           | SECTION_WHEN
           | HIDE
           | DISTINCT
           | DATABASE_SQL
           | LOCAL_SQL
           | ORDER
           | GROUP
           | FOR_UPDATE
           | HAVING
           | INSERTING
           | REPLACING
           | DELETING
           | APPENDING
           | CASE
           | BEGIN
           | COMMIT
           | ROLLBACK
           | WORK
           | LEADINGG
           | TRAILING
           | OFF
           | TO
           | IS
           | IN
           | ARE
           | WITH
           | COLLATE
           | MESSAGEBOX_BUTTONS_VALUES
           | MESSAGEBOX_ICON_VALUES
           | MODEENTRY
           | COLOUR_NAME
           | ADD
           | SUBTRACT
           | MULTIPLY
           | DIVIDE
           | MODULUS
           | GREATERTHAN
           | LESSTHAN
           | EQUALTO
           | NOTEQUALTO
           | NOTEQUALTO
           | GREATERTHANOREQUALTO
           | LESSTHANOREQUALTO
           | AND
           | OR
           | NOT
           | othersymbols_

othersymbols_ ::= SYMBOLS | SEMICOLON | DOT | EQUALTO | LBRACE | RBRACE | LPAREN | RPAREN | COMMA | AT