{
  parserClass="com.bamuel.spllang.parser.SPLParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="SPL"
  psiImplClassSuffix="Impl"
  psiPackage="com.bamuel.spllang.psi"
  psiImplPackage="com.bamuel.spllang.psi.impl"

  elementTypeHolderClass="com.bamuel.spllang.psi.SPLTypes"
  elementTypeClass="com.bamuel.spllang.psi.SPLElementType"
  tokenTypeClass="com.bamuel.spllang.psi.SPLTokenType"
}

splFile ::= item_*

item_ ::=  declaration_ | statement_ | preprocessor_ | function_ | element_
    declaration_ ::= api_ | field_ | local_ | menu_ | mode_ | object_ | parameters_ | procedure_ | returning_ | screen_
    statement_ ::= messagebox_ | message_
    preprocessor_ ::= preprocessors_ //Pre-processor commands summary //todo: split into individual preprocessor commands
    function_ ::= arithmeticfunction_  | datetimefunction_ | environmentfunction_ | stringfunction_

        arithmeticfunction_ ::= aand_ | abs_ | anot_ | aor_ | cos_ | fraction_ | integer_ | lshift_ | max-value_ | max-presentation-value_
        | min-value_ | power-of_ | random_ | rshift_ | sign-of_ | sin_ | smallest-increment_ | square-root_ | sum_ | sum-array_ | tan_

        datetimefunction_ ::= add-month_ | client-date-time-string_ | date-from-date-time_ | date-time_ | date-to-julian_ | day_ | day-name_
        | days-in-month_ | dow_ | gmt_ | hour_ | julian_ | julian-to-date_ | leap-year_ | minute_ | month_ | month-name_ | second_
        | systime_ | time-from-date-time_ | time-zone_ | tod_ | today_ | year_

        environmentfunction_ ::= activepid_ | apiapplication-name_ | batched_ | can-dee_ | check-auth_ | colour-picker_
        | create-db-schema_ | create-db-user_ | currency-sign_ | database-type_ | db-command_ | db-table-name_ | dde-error-status_
        | dde-execute_ | dde-initiate_ | dde-poke_ | dde-request_ | dde-terminate_ | delete-registry-value_ | enable-status-bar_
        | enable-system-menu_ | enable-tool-bar_ | error-description_ | escape_ | exit-status_ | find-parameter_ | getenv_ | get-field-value_
        | get-field-value-numeric_ | get-function-code_ | get-module-code_ | get-param_ | get-registry-enum-key_ | get-registry-enum-value_
        | get-registry-value_ | get-system-metrics_ | gid_ | grant-db-schema_ | hide-dockable-windows_ | idx_ | if-then-else_ | io-count_
        | line-no_ | local-no_ | login-id_ | mail-add-line_ | mail-attach_ | mail-cancel_ | mail-from-name_ | mail-reply-to_ | mail-send_
        | mail-start_ | max-screen-columns_ | max-screen-rows_ | message-status_ | mode-name_ | mouse-column_ | mouse-row_ | node-name_
        | occurrence_ | operating-system_ | page-no_ | param-cnt_ | pid_ | pronto-release_ | prouser-flags_ | refresh-quick-links_
        | report-is-xml_ | review-row_ | revoke-db-schema_ | rgb-to-colour_ | screen-mode_ | search_ | search-mode_ | set-app-user_
        | set-data-area-name_ | set-background-image_ | set-background-url_ | set-environment_ | set-function-code_ | set-help-context_
        | set-keyboard-focus_ | set-module-code_ | set-registry-value_ | set-web-window_ | sleep_ | spool-file-name_ | time-elapsed_
        | transaction-active_ | tty_ | uid_ | user-group_ | valid-activation-key_ | wait-for-input_

        stringfunction_ ::= ascii-char_ | ascii-num_ | base64toblob_| blobappend_ | blobappendbase64_ | blobsection_ | blobtobase64_
        | concat_ |  formatpicture_ | freeblob_ | fstr_ | leftjustify_ | lowercase_ | ltrim_ | maxalphavalue_ | num_ | paramtext_ | pattern_
        | readblobfromfile_ | reserved_ | rightjustify_ | rtrim_ | sizeof_ | sqlsubstring_ | strconcat_ | str_ | strlen_ | substring_
        | substringutf8_ | uppercase_ | validnumber_ | writeblobtofile_ | zstr_

//Arithmetic functions
aand_ ::= AAND LPAREN number_ COMMA number_ RPAREN
abs_ ::= ABS LPAREN number_ RPAREN
anot_ ::= ANOT LPAREN number_ RPAREN
aor_ ::= AOR LPAREN number_ COMMA number_ RPAREN
cos_ ::= COS LPAREN number_ RPAREN
fraction_ ::= FRACTION LPAREN number_ RPAREN
integer_ ::= INTEGER LPAREN number_ RPAREN
lshift_ ::= LSHIFT LPAREN number_ COMMA number_ RPAREN
max-value_ ::= MAX_VALUE LPAREN number_ RPAREN
max-presentation-value_ ::= MAX_PRESENTATION_VALUE LPAREN number_ RPAREN
min-value_ ::= MIN_VALUE LPAREN number_ RPAREN
power-of_ ::= POWER_OF LPAREN number_ COMMA number_ RPAREN
random_ ::= RANDOM LPAREN number_ RPAREN
rshift_ ::= RSHIFT LPAREN number_ COMMA number_ RPAREN
sign-of_ ::= SIGN_OF LPAREN number_ RPAREN
sin_ ::= SIN LPAREN number_ RPAREN
smallest-increment_ ::= SMALLEST_INCREMENT LPAREN number_ RPAREN
square-root_ ::= SQUARE_ROOT LPAREN number_ RPAREN
sum_ ::= SUM LPAREN number_ RPAREN
sum-array_ ::= SUM_ARRAY LPAREN number_ COMMA number_ COMMA number_ RPAREN
tan_ ::= TAN LPAREN number_ RPAREN

//Date and time functions
add-month_ ::= ADD_MONTH LPAREN datestring_ COMMA number_ COMMA number_ RPAREN
client-date-time-string_ ::= CLIENT_DATE_TIME_STRING LPAREN RPAREN
date-from-date-time_ ::= DATE_FROM_DATE_TIME LPAREN datestring_ COMMA boolean_ RPAREN
date-time_ ::= DATE_TIME LPAREN DATE COMMA TIME COMMA boolean_ RPAREN
date-to-julian_ ::= DATE_TO_JULIAN LPAREN string_ RPAREN
day_ ::= DAY LPAREN datestring_ RPAREN
day-name_ ::= DAY_NAME LPAREN datestring_ RPAREN
days-in-month_ ::= DAYS_IN_MONTH LPAREN number_ COMMA number_ RPAREN
dow_ ::= DOW LPAREN datestring_ RPAREN
gmt_ ::= GMT LPAREN RPAREN
hour_ ::= HOUR LPAREN datestring_ RPAREN //todo: stricter TIME
julian_ ::= JULIAN LPAREN number_ COMMA number_ COMMA number_ RPAREN
julian-to-date_ ::= JULIAN_TO_DATE LPAREN datestring_ RPAREN
leap-year_ ::= LEAP_YEAR LPAREN number_ RPAREN
minute_ ::= MINUTE LPAREN datestring_ RPAREN //todo: stricter TIME
month_ ::= MONTH LPAREN datestring_ RPAREN
month-name_ ::= MONTH_NAME LPAREN datestring_ RPAREN
second_ ::= SECOND LPAREN datestring_ RPAREN //todo: stricter TIME
systime_ ::= SYSTIME LPAREN RPAREN
time-from-date-time_ ::= TIME_FROM_DATE_TIME LPAREN datestring_ COMMA boolean_ RPAREN
time-zone_ ::= TIME_ZONE LPAREN RPAREN
tod_ ::= TOD LPAREN RPAREN
today_ ::= TODAY LPAREN RPAREN
year_ ::= YEAR LPAREN datestring_ RPAREN


// Environment function
activepid_ ::= ACTIVE_PID LPAREN number_ RPAREN
apiapplication-name_ ::= API_APPLICATION_NAME LPAREN RPAREN
batched_ ::= BATCHED LPAREN RPAREN
can-dee_ ::= CAN_DDE LPAREN RPAREN
check-auth_ ::= CHECK_AUTH LPAREN number_ RPAREN
colour-picker_ ::= COLOUR_PICKER LPAREN string_ RPAREN
create-db-schema_ ::= CREATE_DB_SCHEMA LPAREN string_ COMMA "SPACES" RPAREN
create-db-user_ ::= CREATE_DB_USER LPAREN string_ COMMA "SPACES" RPAREN
currency-sign_ ::= CURRENCY_SIGN LPAREN RPAREN
database-type_ ::= DATABASE_TYPE LPAREN RPAREN
db-command_ ::= DB_COMMAND LPAREN string_ RPAREN
db-table-name_ ::= DB_TABLE_NAME LPAREN string_ RPAREN
dde-error-status_ ::= DDE_ERROR_STATUS LPAREN RPAREN
dde-execute_ ::= DDE_EXECUTE LPAREN string_ COMMA string_ RPAREN
dde-initiate_ ::= DDE_INITIATE LPAREN string_ COMMA string_ RPAREN
dde-poke_ ::= DDE_POKE LPAREN string_ COMMA string_ COMMA string_ RPAREN
dde-request_ ::= DDE_REQUEST LPAREN string_ COMMA string_ RPAREN
dde-terminate_ ::= DDE_TERMINATE LPAREN string_ RPAREN
delete-registry-value_ ::= DELETE_REGISTRY_VALUE LPAREN string_ RPAREN
enable-status-bar_ ::= ENABLE_STATUS_BAR LPAREN boolean_ RPAREN
enable-system-menu_ ::= ENABLE_SYSTEM_MENU LPAREN boolean_ RPAREN
enable-tool-bar_ ::= ENABLE_TOOL_BAR LPAREN boolean_ RPAREN
error-description_ ::= ERROR_DESCRIPTION LPAREN number_ RPAREN
escape_ ::= ESCAPE LPAREN RPAREN
exit-status_ ::= EXIT_STATUS LPAREN RPAREN
find-parameter_ ::= FIND_PARAMETER LPAREN string_ RPAREN
getenv_ ::= GETENV LPAREN string_ RPAREN
get-field-value_ ::= GET_FIELD_VALUE LPAREN string_ RPAREN
get-field-value-numeric_ ::= GET_FIELD_VALUE_NUMERIC LPAREN string_ RPAREN
get-function-code_ ::= GET_FUNCTION_CODE LPAREN string_ RPAREN
get-module-code_ ::= GET_MODULE_CODE LPAREN string_ RPAREN
get-param_ ::= GET_PARAM LPAREN number_ RPAREN
get-registry-enum-key_ ::= GET_REGISTRY_ENUM_KEY LPAREN string_ COMMA number_ RPAREN
get-registry-enum-value_ ::= GET_REGISTRY_ENUM_VALUE LPAREN string_ COMMA number_ COMMA string_ RPAREN
get-registry-value_ ::= GET_REGISTRY_VALUE LPAREN string_ RPAREN
get-system-metrics_ ::= GET_SYSTEM_METRICS LPAREN number_ RPAREN
gid_ ::= GID LPAREN RPAREN
grant-db-schema_ ::= GRANT_DB_SCHEMA LPAREN string_ COMMA string_ RPAREN
hide-dockable-windows_ ::= HIDE_DOCKABLE_WINDOWS LPAREN (dockableflags_)? RPAREN
dockableflags_ ::= "0"| "non-zero"
idx_ ::= IDX LPAREN string_ (COMMA string_)* RPAREN
if-then-else_ ::= IF_THEN_ELSE LPAREN condition_ COMMA string_ COMMA string_ RPAREN //todo: condition
io-count_ ::= IO_COUNT LPAREN RPAREN
line-no_ ::= LINE_NO LPAREN RPAREN
local-no_ ::= LOCAL_NO_AND_LOCAL_YES LPAREN RPAREN
login-id_ ::= LOGIN_ID LPAREN RPAREN
mail-add-line_ ::= MAIL_ADD_LINE LPAREN string_ RPAREN
mail-attach_ ::= MAIL_ATTACH LPAREN string_ COMMA string_ COMMA number_ COMMA number_ COMMA number_ RPAREN
mail-cancel_ ::= MAIL_CANCEL LPAREN RPAREN
mail-from-name_ ::= MAIL_FROM_NAME LPAREN string_ RPAREN
mail-reply-to_ ::= MAIL_REPLY_TO LPAREN string_ COMMA string_ RPAREN
mail-send_ ::= MAIL_SEND LPAREN string_ COMMA boolean_ COMMA boolean_ RPAREN
mail-start_ ::= MAIL_START LPAREN string_ RPAREN
max-screen-columns_ ::= MAX_SCREEN_COLUMNS LPAREN RPAREN
max-screen-rows_ ::= MAX_SCREEN_ROWS LPAREN RPAREN
message-status_ ::= MESSAGE_STATUS LPAREN RPAREN
mode-name_ ::= MODE_NAME LPAREN RPAREN
mouse-column_ ::= MOUSE_COLUMN LPAREN RPAREN
mouse-row_ ::= MOUSE_ROW LPAREN RPAREN
node-name_ ::= NODE_NAME LPAREN RPAREN
occurrence_ ::= OCCURRENCE LPAREN string_ RPAREN
operating-system_ ::= OPERATING_SYSTEM LPAREN RPAREN
page-no_ ::= PAGE_NO LPAREN string_ RPAREN
param-cnt_ ::= PARAM_CNT LPAREN RPAREN
pid_ ::= PID LPAREN RPAREN
pronto-release_ ::= PRONTO_RELEASE LPAREN RPAREN
prouser-flags_ ::= PROUSER_FLAGS LPAREN RPAREN
refresh-quick-links_ ::= REFRESH_QUICK_LINKS LPAREN RPAREN
report-is-xml_ ::= REPORT_IS_XML LPAREN string_ RPAREN
review-row_ ::= REVIEW_ROW LPAREN RPAREN
revoke-db-schema_ ::= REVOKE_DB_SCHEMA LPAREN string_ COMMA string_ RPAREN
rgb-to-colour_ ::= RGB_TO_COLOUR LPAREN number_ RPAREN
screen-mode_ ::= SCREEN_MODE LPAREN RPAREN
search_ ::= SEARCH LPAREN RPAREN
search-mode_ ::= SEARCH_MODE LPAREN RPAREN
set-app-user_ ::= SET_APP_USER LPAREN string_ RPAREN
set-data-area-name_ ::= SET_DATA_AREA_NAME LPAREN string_ RPAREN
set-background-image_ ::= SET_BACKGROUND_IMAGE LPAREN string_ RPAREN
set-background-url_ ::= SET_BACKGROUND_URL LPAREN string_ COMMA background-urlflags_ RPAREN
background-urlflags_ ::= "1" | "2" | "4" | "8" //todo:  flag settings can be combined by adding the values together.
set-environment_ ::= SET_ENVIRONMENT LPAREN string_ COMMA string_ RPAREN
set-function-code_ ::= SET_FUNCTION_CODE LPAREN string_ RPAREN
set-help-context_ ::= SET_HELP_CONTEXT LPAREN string_ COMMA number_ RPAREN
set-keyboard-focus_ ::= SET_KEYBOARD_FOCUS LPAREN string_ COMMA string_ RPAREN //todo: 2nd string is flag not sure what the values are
set-module-code_ ::= SET_MODULE_CODE LPAREN string_ RPAREN
set-registry-value_ ::= SET_REGISTRY_VALUE LPAREN string_ COMMA string_ RPAREN
set-web-window_ ::= SET_WEB_WINDOW LPAREN string_ COMMA string_ COMMA string_ COMMA webwindowflag_ RPAREN
webwindowflag_ ::= "1" | "2" | "3" | "4" | "8" | "16" | "32" | "64" //todo:  flag settings can be combined by adding the values together.
sleep_ ::= SLEEP LPAREN number_ RPAREN
spool-file-name_ ::= SPOOL_FILE_NAME LPAREN (string_)? RPAREN
time-elapsed_ ::= TIME_ELAPSED LPAREN number_ COMMA number_ RPAREN
transaction-active_ ::= TRANSACTION_ACTIVE LPAREN RPAREN
tty_ ::= TTY LPAREN RPAREN
uid_ ::= UID LPAREN RPAREN
user-group_ ::= USER_GROUP LPAREN RPAREN
valid-activation-key_ ::= VALID_ACTIVATION_KEY LPAREN string_ COMMA string_ RPAREN
wait-for-input_ ::= WAIT_FOR_INPUT LPAREN RPAREN


//String functions
ascii-char_ ::= ASCII_CHAR LPAREN number_ RPAREN
ascii-num_ ::= ASCII_NUM LPAREN string_ RPAREN
base64toblob_ ::= BASE64TOBLOB LPAREN string_ COMMA string_ RPAREN
blobappend_ ::= BLOBAPPEND LPAREN string_ COMMA string_ RPAREN
blobappendbase64_ ::= BLOBAPPENDBASE64 LPAREN string_ COMMA string_ RPAREN
blobsection_ ::= BLOBSECTION LPAREN string_ COMMA string_ COMMA string_ COMMA string_ RPAREN
blobtobase64_ ::= BLOBTOBASE64 LPAREN string_ COMMA string_ COMMA string_ RPAREN
concat_ ::= CONCAT LPAREN string_ (COMMA? string_)* RPAREN
formatpicture_ ::= FORMATPICTURE LPAREN string_ COMMA picture_ RPAREN
freeblob_ ::= FREEBLOB LPAREN string_ RPAREN
fstr_ ::= FSTR LPAREN number_ COMMA number_ COMMA number_ RPAREN
leftjustify_ ::= LEFTJUSTIFY LPAREN string_ RPAREN
lowercase_ ::= LOWERCASE LPAREN string_ RPAREN
ltrim_ ::= LTRIM LPAREN string_ RPAREN
maxalphavalue_ ::= MAXALPHAVALUE LPAREN number_ RPAREN
num_ ::= NUM LPAREN string_ RPAREN
paramtext_ ::= PARAMTEXT LPAREN STRING (COMMA param_list_)? RPAREN
param_list_ ::= string_ (COMMA string_)*
pattern_ ::= PATTERN LPAREN string_ COMMA string_  RPAREN
readblobfromfile_ ::= READBLOBFROMFILE LPAREN string_ COMMA string_ RPAREN
reserved_ ::= RESERVED LPAREN string_ RPAREN
rightjustify_ ::= RIGHTJUSTIFY LPAREN string_ RPAREN
rtrim_ ::= RTRIM LPAREN string_ RPAREN
sizeof_ ::= SIZEOF LPAREN string_ RPAREN
sqlsubstring_ ::= SQLSUBSTRING LPAREN string_ COMMA number_ COMMA number_ RPAREN
strconcat_ ::= STRCONCAT LPAREN string_ (COMMA? string_)* RPAREN
str_ ::= STR_FUNC LPAREN number_ RPAREN
strlen_ ::= STRLEN LPAREN string_ RPAREN
substring_ ::= SUBSTRING LPAREN string_ COMMA number_ COMMA number_ RPAREN
substringutf8_ ::= SUBSTRINGUTF8 LPAREN string_ COMMA number_ COMMA number_ COMMA number_ RPAREN
uppercase_ ::= UPPERCASE LPAREN string_ RPAREN
validnumber_ ::= VALIDNUMBER LPAREN string_ RPAREN
writeblobtofile_ ::= WRITEBLOBTOFILE LPAREN string_ COMMA string_ RPAREN
zstr_ ::= ZSTR LPAREN number_ COMMA number_ COMMA number_ RPAREN


// Message rule
message_ ::= MESSAGE (string_)? (NOBELL)?

// Preprocessor rule
preprocessors_ ::= PREPROCESSOR (IDENTIFIER | STRING)


// Screen rule
screen_ ::= SCREEN IDENTIFIER (SCREEN_RESPONSIVE)? (window_)? (windowpositision_)? (screentitle_)? (screenprimary_)? (screenselect_)? (screenquicklink_)? (colour_)? (screenreview_)? (screenallowed_)? (SCREEN_PROMPT_FOR_SEARCH)? (SCREEN_FIND_FOR_CURRENCY)? (screenprompt_)? (screendatagrid_)? (screenreviewoccurs)? (SCREEN_REVIEW_FROM_START)? (SCREEN_NO_REVIEW_ROW_SEPARATORS)? (SCREEN_NO_REVIEW_COLUMN_SEPARATORS)? (SCREEN_NO_REVIEW_SEPARATORS)? (SCREEN_START_ON_CURRENT_RECORD)? (SCREEN_LEAVE_PARENT_SCREEN)? (screenwhen_)? (local_)? (parameters_)? (returning_)? (STOP_EXIT_ALL_KEY)? (SCREEN_POSITION_ON_OK)? (SCREEN_STAY_IN_CORRECT)? (SCREEN_FORM_ENTRY)? (export_)? (screenhelpcontext_)? (before_)? (detail_)? (after_)? SCREEN_END

screentitle_ ::= TITLE ("is")? string_
screenprimary_ ::= SCREEN_PRIMARY IDENTIFIER (SCREEN_ON)? (SCREEN_SAME_DIFFERENT (IDENTIFIER fieldclauses_)*)?
screenselect_ ::= SCREEN_SELECT selectclauses_
screenquicklink_ ::= SCREEN_QUICK_LINK ("on")? IDENTIFIER
screenreview_ ::= SCREEN_REVIEW ("is")? "colour" ("on")? IDENTIFIER
screenallowed_ ::= SCREEN_ALLOWED ("is"|"are")? ("FIND"|"NEXT"|"PREV"|"NEXT-SCR"|"PREV-SCR"|"SEARCH"|"ENTRY"|"CORRECT"|"REMOVE"|"find"|"next"|"prev"|"next-scr"|"prev-scr"|"search"|"entry"|"correct"|"remove") IDENTIFIER* //todo: [mode-name ...]]
screenprompt_ ::= PROMPT rowcol_
screendatagrid_ ::= SCREEN_DATA_GRID item_* //todo: datagrid
screenreviewoccurs ::= SCREEN_REVIEW_OCCURS number_ ("by" number_)?
screenwhen_ ::= WHEN item_* //todo: conditon

// API rule
api_ ::= API IDENTIFIER item_* API_END //todo: procedural-statements

// Field rule
field_ ::= FIELD (IDENTIFIER fieldclauses_)*
fieldclauses_ ::= (fieldtype_)? (fieldpic_)? (fieldoccurs_)? (fieldlike_)? (fieldcase_)? (JUSTIFY)? (USE_NAME_IN_DB)? (fielddbcolumnname_)? (fielddrillback_)?
fieldtype_ ::= TYPE ("is")? datatypes_
datatypes_ ::= ("NUMERIC"|"DECIMAL"|"MONEY"|"FLOATING"|"ALPHA"|"STRING"|"VARCHAR"|"BLOB"|"XML-HANDLE"|"DATE"|"TIME"|"DATE-TIME"|"DATETIME"|"DATE_TIME"|"LOCAL-DATE-TIME"|"BOOLEAN"|"COLOUR"|"COLOR"|"OLE-INTERFACE"|"numeric"|"decimal"|"money"|"floating"|"alpha"|"string"|"varchar"|"blob"|"xml-handle"|"date"|"time"|"date-time"|"datetime"|"date_time"|"local-date-time"|"boolean"|"colour"|"color"|"ole-interface")
fieldpic_ ::= PIC ("is")? picture_
fieldoccurs_ ::= OCCURS NUMBER ("times")?
fieldlike_ ::= LIKE IDENTIFIER
fieldcase_ ::= ("UPPERCASE" | "LOWERCASE" | "uppercase" | "lowercase")
fielddbcolumnname_ ::= DB_COLUMN_NAME ("is")? string_
fielddrillback_ ::= DRILL_BACK ("is")? string_

// Local field rule
local_ ::= LOCAL (FIELD)? (IDENTIFIER fieldclauses_)*

// Menu rule
menu_ ::= MENU IDENTIFIER menucaluses_ MENU_END
menucaluses_ ::= (window_)? (windowpositision_)? (local_)? (parameters_)? (returning_)? (menubuttonwidth_)? (STOP_EXIT_ALL_KEY)? (TITLE ("is")? string_)? (TREEMENU)? (NOHIDE)? (colour_)? (export_)? (helpcontext_)? (before_)? (detail_)? (after_)?
menubuttonwidth_ ::= MENU_BUTTON_WIDTH ("is")? number_

// Mode rule
mode_ ::= MODE IDENTIFIER modeclauses_
modeclauses_ ::= (modeprompt_)? (help_)? (security_)? (modeentry_)? (process_)? (modecurrency_)? (LOCK)? (modeperform_)? (modewhen_)? (colour_)? (modeicon_)? (alwaysshowaddnohide_)?
modeprompt_ ::= PROMPT ("is")? string_
help_ ::= HELP ("is")? string_
security_ ::= SECURITY ("is")? number_
modeentry_ ::= MODEENTRY
process_ ::= PROCESS
modecurrency_ ::= MODECURRENCY
modeperform_ ::= PERFORM IDENTIFIER
modewhen_ ::= WHEN item_*
modeicon_ ::= ICON ("is")? modeiconlist_
modeiconlist_ ::= "FOLDER-ICON"
                | "ADMIN-FOLDER-ICON"
                | "REPORT-FOLDER-ICON"
                | "ADMIN-ICON"
                | "REPORT-ICON"
                | "SCREEN-ICON"
                | "TRANSACTION-ICON"
                | "PERIOD-END-ICON"
                | "QUESTION-ICON"
                | "BLANK-ICON"
                | "FAVOURITES-FOLDER-ICON"
                | "LOCKED-FOLDER-ICON"
                | "BLUE-FOLDER-ICON"
                | "RED-FOLDER-ICON"
                | "GREEN-FOLDER-ICON"
                | "ENQUIRY-FOLDER-ICON"
alwaysshowaddnohide_ ::= (ALWAYS_SHOW)? (ALWAYS_ADD)? (NOHIDE)?


// Object rule
object_ ::= OBJECT (IDENTIFIER objectclauses_)*
objectclauses_ ::= (objectlike_)? (objecttype_)? (objectseparator_)? (objectfile_)? (objectrecord_)? (objectkey_)? (NOJOINS)? (NOROWID)?
objectlike_ ::= LIKE IDENTIFIER
objecttype_ ::= TYPE ("is")? filetypes_
filetypes_ ::= ("EXTERNAL"|"TEXT"|"SEQUENTIAL"|"FIXED-LENGTH-TEXT"|"INDEXED"|"ISAM"|"PRN"|"CSV"|"DB-SEQUENTIAL"|"MEMORY"|"external"|"text"|"sequential"|"fixed-length-text"|"indexed"|"isam"|"prn"|"csv"|"db-sequential"|"memory")
objectseparator_ ::= SEPARATOR ("is")? string_
objectfile_ ::= FILE ("is")? string_
objectrecord_ ::= RECORD ("is")? (IDENTIFIER fieldclauses_)* RECORD_END
objectkey_ ::= KEY ("is")? (IDENTIFIER (DESC)? (UNIQUE)? (DB_INDEX_ONLY)? (COMPRESS)?)*

// Parameters rule
parameters_ ::= PARAMETERS ("are"|"is")? (IDENTIFIER fieldclauses_)*

// Returning rule
returning_ ::= RETURNING (IDENTIFIER fieldclauses_)*

// Procedure rule
procedure_ ::= PROCEDURE IDENTIFIER procedureclauses_ PROCEDURE_END//todo: procedural-statements
procedureclauses_ ::= (window_)? (relative_)? (NOHIDE)? (windowpositision_)? (colour_)? (local_)? (parameters_)? (returning_)? (STOP_EXIT_ALL_KEY)? (TITLE string_)? (export_)? (AUTO_TRANSACTION)? (helpcontext_)? item_*

// Other rules
export_ ::= EXPORT (CAN_OVERRIDE)?
colour_ ::= COLOUR ("is")? IDENTIFIER ("on" IDENTIFIER)?
helpcontext_ ::= SCREEN_HELP_CONTEXT ("is") string_ string_
window_ ::= WINDOW rowcol_ "to" rowcol_ (relative_)?
relative_ ::= RELATIVE_TO "to" rowcol_
windowpositision_ ::= WINDOW_POSITION ("is")? number_
before_ ::= BEFORE item_* //todo: procedural-statements
detail_ ::= DETAIL item_* //todo: procedural-statements
after_ ::= AFTER item_* //todo: procedural-statements

// Messagebox rule
messagebox_ ::= MESSAGEBOX string_ messsageboxtitle_? messageboxbuttons_? messageboxdefault_? messageboxicon_? messageboxtag_? messageboxhelpcontext_? messageboxoptional_? messageboxbell_? item_*

messsageboxtitle_ ::= TITLE ("is")? string_
messageboxbuttons_ ::= MESSAGEBOX_BUTTONS MESSAGEBOX_BUTTONS_VALUES
messageboxdefault_ ::= DEFAULT ("is")? MESSAGEBOX_BUTTONS_VALUES
messageboxicon_ ::= ICON ("is")? MESSAGEBOX_ICON_VALUES
messageboxtag_ ::= TAG ("is")? NUMBER
messageboxhelpcontext_ ::= HELP_CONTEXT string_
messageboxoptional_ ::= OPTIONAL
messageboxbell_ ::= BELL


//row and col
//Syntax @row,col
rowcol_ ::= AT NUMBER COMMA NUMBER
selectclauses_ ::= "SELECT" item_* //todo: sql select

string_ ::= STRING | IDENTIFIER | BAD_CHARACTER | datetimefunction_ | stringfunction_ | environmentfunction_
number_ ::= NUMBER | IDENTIFIER | arithmeticfunction_ | datetimefunction_ | environmentfunction_
boolean_ ::= "TRUE" | "FALSE" | "true" | "false" | "1" | "0"
datestring_ ::= DATE | TIME | IDENTIFIER | datetimefunction_
condition_ ::= item_*
//The following picture string characters are used to specify the format of a field being defined.
// They indicate the size of the field, number of integer/decimal places and whether the field allows negative amounts.
// todo: add more picture string characters, this covers the basics.
picture_ ::= pic_group_ | pic_words
pic_words ::= "ddmmmyybhh:mm"| "HH:MM:SS" // Date and time format
pic_group_ ::= (NUMBER | IDENTIFIER) (LPAREN number_ RPAREN)? (IDENTIFIER LPAREN number_ RPAREN)?

element_ ::= FUNCTION_DECLARATION
           | KEYWORD
           | STRING
           | NUMBER
           | IDENTIFIER
           | COMMENT
           | BLOCK_COMMENT
           | TITLE
           | DEFAULT
           | WINDOW
           | PROMPT
           | DETAIL
           | ICON
           | TAG
           | HELP_CONTEXT
           | OPTIONAL
           | BELL
           | NOBELL
           | COLOUR
           | TYPE
           | PIC
           | OCCURS
           | LIKE
           | JUSTIFY
           | USE_NAME_IN_DB
           | DB_COLUMN_NAME
           | DRILL_BACK
           | RELATIVE_TO
           | WINDOW_POSITION
           | PARAMETERS
           | RETURNING
           | STOP_EXIT_ALL_KEY
           | EXPORT
           | CAN_OVERRIDE
           | BEFORE
           | AFTER
           | SEPARATOR
           | FILE
           | RECORD
           | RECORD_END
           | KEY
           | DESC
           | UNIQUE
           | DB_INDEX_ONLY
           | COMPRESS
           | NOJOINS
           | NOROWID
           | HELP
           | PROCESS
           | MODEENTRY
           | MODECURRENCY
           | LOCK
           | PERFORM
           | ALWAYS_SHOW
           | ALWAYS_ADD
           | SCREEN_PRIMARY
           | LOCAL
           | SCREEN_ALLOWED
           | MESSAGEBOX_BUTTONS
           | MESSAGEBOX_BUTTONS_VALUES
           | MESSAGEBOX_ICON_VALUES
           | othersymbols_

othersymbols_ ::= SYMBOLS | SEMICOLON | DOT | EQUALS | LBRACE | RBRACE | LPAREN | RPAREN | COMMA | AT